### ISSUE TITLE
Including Nimbus SDK breaks offline builds

### ISSUE THREAD

**Issue by gk-tpo** [mozilla/application-services#3732] opened 2020-11-24 16:25 UTC
We use offline builds for Tor Browser which worked reasonably well until v63.0.0 which was a requirement for Fenix 83. With the preparation for Fenix 84 we plan to switch to v67.0.0 which breaks our offline builds.

In order to build in offline mode here is what we are doing for the Rust side of things:

1) We vendor in all necessary crates by running `cargo vendor vendor` in the top-level directory.
2) We extract all the vendored crates into our container at `/var/tmp/build/application-services` and then make sure our vendored crates are used for offline building by doing
```
cat >> .cargo/config << 'EOF'

[source.crates-io]
replace-with = "vendored-sources"

[source.vendored-sources]
directory = "/var/tmp/build/application-services/vendor"

[net]
offline=true
EOF
```
That worked so far but with v67.0.0 the build breaks with
```
2020-11-24T12:23:52.993+0000 [ERROR] [system.err]   thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Failed to run cargo metadata: CargoMetadata { stderr: "error: failed to get `viaduct` as a dependency of package `nimbus-sdk v0.5.1 (/var/tmp/build/application-services/components/external/nimbus-sdk/nimbus)`\n\nCaused by:\n  failed to load source for dependency `viaduct`\n\nCaused by:\n  Unable to update https://github.com/mozilla/application-services?rev=8a576fbe79199fa8664f64285524017f74ebcc5f#8a576fbe\n\nCaused by:\n  can\'t checkout from \'https://github.com/mozilla/application-services\': you are in the offline mode (--offline)\n" }', components/external/nimbus-sdk/nimbus/build.rs:6:60
```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1910)
┆Epic: local development, ci and release (backlog)
┆Sprint: Backlog

**Comment by gk-tpo** [comment] 2020-11-24 16:26
I am happy to test any workarounds/custom patches, in case there are any as this issue is currently blocking us from moving to Fenix 84

**Comment by rfk** [comment] 2020-11-30 04:56
Is this failure happening during `cargo vendor` or during the subsequent `cargo build`? I interpret the above as meaning it happened in `cargo build` but am not quite sure if that's right.

If so, I suspect this is caused by the [nimbus build.rs script](https://github.com/mozilla/nimbus-sdk/blob/2f49f46ef07caf52c8259c34ca4ba3b019432f55/nimbus/build.rs#L6), which calls [uniffi_build::generate_scaffolding](https://github.com/mozilla/uniffi-rs/blob/4812fc2494d6db6e1800c0da8f7eba69b235451c/uniffi_build/src/lib.rs#L28), which tries to [use `cargo metadata`](https://github.com/mozilla/uniffi-rs/blob/4812fc2494d6db6e1800c0da8f7eba69b235451c/uniffi_bindgen/src/lib.rs#L157) to do some version compatibility checks.

One thing to try would be to include the `nimbus-sdk` crate in the application-services workspace, by:

* removing it from the list of excludes [here](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L52).
* adding `components/external/nimbus-sdk/nimbus` to the list of workspace members [here](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L3).

This might cause `cargo metadata` to pick up the [special patching logic](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L121) that we do for the `viaduct` crate, to resolve a weird circular dependency between `application-services` and `nimbus-sdk`.

If that works, I think I'd be happy to include it in our default config to keeps things simple.

**Comment by gk-tpo** [comment] 2020-12-01 08:17
> Is this failure happening during `cargo vendor` or during the subsequent `cargo build`? I interpret the above as meaning it happened in `cargo build` but am not quite sure if that's right.

That's correct. `cargo vendor` is behaving fine. It's the build that breaks.
 
[snip]
 
> One thing to try would be to include the `nimbus-sdk` crate in the application-services workspace, by:
> 
>     * removing it from the list of excludes [here](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L52).
> 
>     * adding `components/external/nimbus-sdk/nimbus` to the list of workspace members [here](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L3).
> 
> 
> This might cause `cargo metadata` to pick up the [special patching logic](https://github.com/mozilla/application-services/blob/02e6973763563307c7ca99dbbbc294ee77b9d546/Cargo.toml#L121) that we do for the `viaduct` crate, to resolve a weird circular dependency between `application-services` and `nimbus-sdk`.
> 
> If that works, I think I'd be happy to include it in our default config to keeps things simple.

It does not seems so. Here is the patch I deployed:
```
diff --git a/Cargo.lock b/Cargo.lock
index 21244f27..120c38fb 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1838,21 +1838,26 @@ name = "nimbus-sdk"
 version = "0.5.1"
 dependencies = [
  "anyhow",
+ "clap",
+ "env_logger",
  "hex",
  "jexl-eval",
  "log 0.4.11",
+ "mockito",
  "once_cell",
  "rkv",
  "serde",
  "serde_derive",
  "serde_json",
  "sha2",
+ "tempdir",
  "thiserror",
  "uniffi",
  "uniffi_build",
  "url",
  "uuid",
  "viaduct",
+ "viaduct-reqwest",
 ]
 
 [[package]]
diff --git a/Cargo.toml b/Cargo.toml
index 33c2c798..6bea4ad5 100644
--- a/Cargo.toml
+++ b/Cargo.toml
@@ -2,6 +2,7 @@
 # Note: Any additions here should be repeated in default-members below.
 members = [
     "components/autofill",
+    "components/external/nimbus-sdk/nimbus",
     "components/fxa-client",
     "components/fxa-client/ffi",
     "components/logins",
@@ -49,7 +50,6 @@ members = [
 # been written with that in mind. They might work, but they might not.
 exclude = [
     "components/external/glean/",
-    "components/external/nimbus-sdk/",
 ]
 
 # The `default-members` are the things that are built/tested when you run `cargo
@@ -78,6 +78,7 @@ exclude = [
 # use the full member set.
 default-members = [
     "components/autofill",
+    "components/external/nimbus-sdk/nimbus",
     "components/fxa-client",
     "components/fxa-client/ffi",
     "components/logins",
```
(the `Cargo.lock` changes came due to running `cargo vendor`).

And here is what the build error says:
```
> Task :full-megazord:cargoBuildArm FAILED
error: failed to get `viaduct-reqwest` as a dependency of package `nimbus-sdk v0.5.1 (/var/tmp/build/application-services/components/external/nimbus-sdk/nimbus)`

Caused by:
  failed to load source for dependency `viaduct-reqwest`

Caused by:
  Unable to update https://github.com/mozilla/application-services?rev=8a576fbe79199fa8664f64285524017f74ebcc5f

Caused by:
  can't checkout from 'https://github.com/mozilla/application-services': you are in the offline mode (--offline)
```

**Comment by gk-tpo** [comment] 2020-12-01 08:59
FWIW: the workaround I am currently using/testing is patching the local checkout of the Nimbus SDK by pointing to `application-services`' `viaduct` and `viaduct-request` like so:
```
diff --git a/nimbus/Cargo.toml b/nimbus/Cargo.toml
index 3f118b7..0d0fa9b 100644
--- a/nimbus/Cargo.toml
+++ b/nimbus/Cargo.toml
@@ -25,7 +25,7 @@ serde_derive = "1"
 serde_json = "1"
 log = "0.4"
 # Viaduct locked to version same version of app-services as mozilla-central
-viaduct = { git = "https://github.com/mozilla/application-services", rev = "8a576fbe79199fa8664f64285524017f74ebcc5f"}
+viaduct = { path = "../../../viaduct" }
 thiserror = "1"
 url = "2.1"
 rkv = "0.15"
@@ -40,7 +40,7 @@ uniffi = "0.5"
 uniffi_build = { version = "0.5", features = [ "builtin-bindgen" ] }
 
 [dev-dependencies]
-viaduct-reqwest = { git = "https://github.com/mozilla/application-services", rev = "8a576fbe79199fa8664f64285524017f74ebcc5f"}
+viaduct-reqwest = { path = "../../../support/viaduct-reqwest" }
```
That builds offline and the final .apk is running fine under cursory testing, but something less ugly to have would be preferable. :)

**Comment by rfk** [comment] 2020-12-01 20:27
Thanks for trying it out. That ugly workaround is what I was hoping would happen in a slightly cleaner fashion when you included it in the workspace, but c'est la vie. I'll try to find some time to poke at this and repro locally so I can work out a fix.

**Comment by rfk** [comment] 2021-03-25 03:43
As of #3963, nimbus-sdk has been merged into this repo, and as a result it no longer depends on `viaduct` via a github URL. Could you please check whether this has fixed the issue here with offline builds?

**Comment by boklm** [comment] 2021-04-30 14:39
> As of #3963, nimbus-sdk has been merged into this repo, and as a result it no longer depends on `viaduct` via a github URL. Could you please check whether this has fixed the issue here with offline builds?

I can confirm that this fixed the issue with offline builds: https://gitlab.torproject.org/tpo/applications/tor-browser-build/-/issues/40269#note_2734013

**Comment by mhammond** [comment] 2021-05-03 02:37
Thanks for getting back to us!

**Closed by mhammond** 2021-05-03 02:37 UTC
Labels: important-not-urgent
