### ISSUE TITLE
Irregularities in Send-Tab metrics

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#3722] opened 2020-11-16 19:33 UTC
I noticed a few oddities in the  Send-Tab dashboard. Since the iOS metrics have been weird for a bit I'm not sure if there's a known issue at play.

[https://sql.telemetry.mozilla.org/queries/73067#183006](https://sql.telemetry.mozilla.org/queries/73067#183006)

[https://sql.telemetry.mozilla.org/queries/74214#185545](https://sql.telemetry.mozilla.org/queries/74214#185545)

[https://sql.telemetry.mozilla.org/queries/73067#183005](https://sql.telemetry.mozilla.org/queries/73067#183005)

[https://sql.telemetry.mozilla.org/queries/73064#183000](https://sql.telemetry.mozilla.org/queries/73064#183000)

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2577)
┆Epic: Important backlog

**Comment by rfk** [comment] 2020-11-17 22:54
I've combined the "other" and "unknown" categories in some of these graphs, since the oddities seemed to be caused by low-volume "other" clients.

**Comment by tarikeshaq** [comment] 2023-09-27 02:49
We've gone through quite a few changes since this was filed, especially for Firefox iOS and charts look more or less as expected, closing

**Closed by tarikeshaq** 2023-09-27 02:49 UTC
Labels: discuss
