### ISSUE TITLE
Update XCFramework documentation to better detail using local packages

### ISSUE THREAD

**Issue by skhamis** [mozilla/application-services#4928] opened 2022-04-28 19:12 UTC
It's not immediately clear that trying to use a local SPM package created from the steps here: https://github.com/mozilla/application-services/tree/main/megazords/ios-rust is not ideal when switching the release version in XCode.

When trying to switch it in XCode -- you will have to do it for Firefox for iOs's multiple targets (they have 7+ targets).

Instead we should update the documentation to explain that the better way is:

1. Editing the .pbxproj file from `https://github.com/mozilla/rust-components-swift/` to `{path-to-your-ci-build-or-local-build}` where it'll cause much less headache.

2.  Reset the package cache (in Xcode) to fetch the new versions

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3153)
┆epic: Rust Components on iOS developer experience
┆sprintEndDate: 2022-05-13

**Comment by tarikeshaq** [comment] 2022-05-09 21:43
I'll close this a duplicate of #4825, I'm working on that now, and it should cover doing the what this ticket requires using some scripts that were landed

**Closed by tarikeshaq** 2022-05-09 21:43 UTC
