### ISSUE TITLE
Build script fails because of an invalid SQLCipher checksum

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#5354] opened 2023-01-30 19:39 UTC
All of our CI started failing because the checksum operation for SQLCipher version 4.5.2 started failing.

The build script looks for a cached SQLCipher source file, if it can't find one it downloads from `https://github.com/sqlcipher/sqlcipher/archive/v4.5.2.tar.gz` and checksums the file, and verifies the checksum equals `6925f012deb5582e39761a7d4816883cc15b41851a8e70b447c223b8ef406e2a`

This was working fine until earlier today, when the checksum is now `ac477df20dddc957da78fc7065c83f0d75f8b7e4472ad0721ea9318ec8126086`. This could mean that the file got corrupted, or got re-uploaded.

@bendk already asked in an SQLCipher form but opening this for tracking here.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3576)
┆Epic: Important backlog
┆Sprint End Date: 2023-02-02

**Comment by bendk** [comment] 2023-01-31 15:37
Caused by this: https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/

This was fixed by the above PR, which switches our scripts to download from the official website.

**Closed by bendk** 2023-01-31 15:37 UTC
