### ISSUE TITLE
places::api::places_api - get_registered_sync_engine: no PlacesApi registered

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#4902] opened 2022-04-12 19:34 UTC
This is affecting ~10% of our Nightly users. From the sentry data, looks like a recent regression/issue - started in 91.1.0 A-S, perhaps?

https://sentry.io/organizations/mozilla/issues/3150576674/?project=6295546&query=is%3Aunresolved

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3130)
┆sprintEndDate: 2022-04-29

**Comment by skhamis** [comment] 2022-04-12 20:08
Thanks for logging this. Just an initial brain dump:

android-components believes it successfully registers the History engine here: 
https://github.com/mozilla-mobile/android-components/blob/854086047fdc840cdf90e734094bb6ad4a67d42a/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt#L339-L340

But the actual sync call fails here: https://github.com/mozilla-mobile/android-components/blob/9111909ae402ce565b10aef868afaae14e02fa5d/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt#L434

Code that's throwing the error (not necessarily the culprit): https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/places/src/api/places_api.rs#L45-L50

For some reason the `PLACES_API_FOR_SYNC_MANAGER` is being dropping prematurely and we don't have a proper way of reestablishing that connection before the sync happens.

**Comment by grigoryk** [comment] 2022-04-12 20:20
A note about `syncableStores` in https://github.com/mozilla-mobile/android-components/blob/854086047fdc840cdf90e734094bb6ad4a67d42a/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/sync/WorkManagerSyncManager.kt#L336 - it may not contain the whole set of engines. In https://github.com/mozilla-mobile/android-components/pull/11805 we allowed manually specifying which engines are to be synced (before that change, it was always every engine).

**Comment by grigoryk** [comment] 2022-04-14 03:03
@skhamis could we be hitting https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/places/src/api/places_api.rs#L45-L50 (trying to access PLACES_API_FOR_SYNC_MANAGER) in cases where we're just trying to sync a single non-places engine, e.g. tabs? That's the new behaviour in Fenix now - on startup, we try to only sync tabs before performing a full sync.

**Comment by mhammond** [comment] 2022-04-14 04:02
I don't *think* that is possible - at https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/sync_manager/src/manager.rs#L32-L41, we should only call that places function is bookmarks or history were explicitly requested.

(although obviously I don't understand what can cause it, so there might be something related to that)

**Comment by mhammond** [comment] 2022-04-14 05:36
In my logcat, I see `places: finishing writable database open` at least 3 times as the app starts. I also see, eg, `syncmanager_88ca_SyncManager_new` twice. At face value, it looks like what we think are singletons actually aren't? I'll keep digging though...

**Comment by mhammond** [comment] 2022-04-14 08:20
Can't reproduce that "3 times" - that run didn't fail, though, but it's odd.

I tried to induce it by triggering various failures etc, but failed. Options seem to be:
* a-c dropped it's `places` - can't see how that can happen without places being entirely broken.
* somehow multiple `places` objects, but our rust code protects against that assuming the same db path.
* a-c fails to call `places.registerWithSyncManager()`, but I can't see how that's possible - in-fact it will be called at least twice (once by history, once by bookmarks). I can simulate that and see the symptoms, but can't explain how it might actually happen.

**Comment by Amejia481** [comment] 2022-04-14 18:04
👋🏽 
@mhammond and @skhamis.
I was taking a look and so far it looks like the reports are only coming from A-S `91.1.1`, could it be a regression on that version? I'm still trying to reproduce the issue locally to see if it's on a lower version.

**Comment by grigoryk** [comment] 2022-04-14 20:32
@mhammond FWIW, I think your patch w/ sync engine breadcrumbs would be very helpful to have here - perhaps we'll see some correlations with a specific set of engines being synced? Maybe we can land it to help debugging on Nightly? https://github.com/mozilla-mobile/android-components/pull/11874 Although, we really only have two options, _I think_ - all engines enumerated, or a single tabs engine.

**Comment by csadilek** [comment] 2022-04-14 22:21
Drive-by 🚗:

> reports are only coming from A-S 91.1.1

We actually see them for `91.1.0` as well, which we only used for a short amount of time. Just in case you end up bisecting so you don't miss commits: https://sentry.io/organizations/mozilla/issues/3150576674/tags/ac.as.build_version/?project=6295546

https://github.com/mozilla-mobile/android-components/pull/11805 landed in release 99 which uses A-S 91.1.1 as well, but we don't seen any reports there, despite using the same A-C version.

**Comment by skhamis** [comment] 2022-04-15 01:59
So I was finally able to reproduce this semi-frequently and I think it has something to do with background sync behavior (still haven't found the exact culprit). The repro is as follow:

1. Have a bunch of tabs open 
2. Switch to a new tab/homescreen page
3. Minimize firefox and or switch apps switch apps
4. Go back to firefox after awhile 
5. Minimize firefox again
 -- Logcat gives me the error

(I gave extra space to where interesting events/exceptions happened)
```
022-04-14 15:44:22.688 32565-32601/org.mozilla.fenix.debug D/SyncWorker: Starting sync... Tagged as: [Immediate, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Common]
2022-04-14 15:44:22.697 32565-32601/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_new
2022-04-14 15:44:22.697 32565-32601/org.mozilla.fenix.debug D/tabs: tabs_14ee_TabsStore_register_with_sync_manager
2022-04-14 15:44:22.707 32565-32601/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_sync


2022-04-14 15:44:22.709 32565-32601/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-14 15:44:22.709 32565-32601/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered
2022-04-14 15:44:22.710 32565-32601/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-14 15:44:22.710 32565-32601/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered



2022-04-14 15:44:22.711 32565-32601/org.mozilla.fenix.debug D/sync_manager::manager: Not under backoff
2022-04-14 15:44:22.711 32565-32601/org.mozilla.fenix.debug I/sync_manager::manager: No backoff in effect (or we decided to ignore it), starting sync
2022-04-14 15:44:22.712 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing 1 engines
2022-04-14 15:44:22.712 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Loading/initializing persisted state
2022-04-14 15:44:22.712 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Preparing client info
2022-04-14 15:44:22.712 32565-32601/org.mozilla.fenix.debug D/sync15::sync_multiple: mem_cached_state was stale or missing, need setup
2022-04-14 15:44:22.717 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Entering sync state machine
2022-04-14 15:44:22.717 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Advancing state machine to ready (full)
2022-04-14 15:44:22.717 32565-32601/org.mozilla.fenix.debug D/sync15::token: Fetching token from https://token.services.mozilla.com/1.0/sync/1.5
2022-04-14 15:44:23.385 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/info/configuration", incoming x-last-modified=ServerTimestamp(0)
2022-04-14 15:44:23.489 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/info/collections", incoming x-last-modified=ServerTimestamp(1649987040780)
2022-04-14 15:44:23.589 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/meta/global", incoming x-last-modified=ServerTimestamp(1649980347780)
2022-04-14 15:44:23.589 32565-32601/org.mozilla.fenix.debug D/sync15::client: Got meta global with modified = 1649980347.78; last-modified = 1649980347.78
2022-04-14 15:44:23.589 32565-32601/org.mozilla.fenix.debug I/sync15::state: Have info/collections and meta/global. Computing new engine states
2022-04-14 15:44:23.590 32565-32601/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"prefs", "passwords", "addons"}, remote: Some(RemoteEngineState { info_collections: {"forms", "history", "tabs", "bookmarks", "meta", "crypto", "clients"}, declined: {"passwords", "prefs", "addons"} }), user_changes: {} }
2022-04-14 15:44:23.590 32565-32601/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: output EngineStateOutput { declined: {"addons", "passwords", "prefs"}, changes_needed: EngineChangesNeeded { local_resets: {}, remote_wipes: {} } }
2022-04-14 15:44:23.687 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/crypto/keys", incoming x-last-modified=ServerTimestamp(1646340669080)
2022-04-14 15:44:23.687 32565-32601/org.mozilla.fenix.debug D/sync15::sync_multiple: Declined engines list after state machine set to: Some(["addons", "passwords", "prefs"])
2022-04-14 15:44:23.687 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Synchronizing clients engine
2022-04-14 15:44:23.687 32565-32601/org.mozilla.fenix.debug I/sync15::clients::engine: Syncing collection clients
2022-04-14 15:44:23.799 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/clients", incoming x-last-modified=ServerTimestamp(1649986859150)
2022-04-14 15:44:23.799 32565-32601/org.mozilla.fenix.debug D/sync15::clients::engine: Found my record on the server
2022-04-14 15:44:23.800 32565-32601/org.mozilla.fenix.debug D/sync15::clients::engine: Will update our client record on the server
2022-04-14 15:44:23.801 32565-32601/org.mozilla.fenix.debug I/sync15::request: Posting 1 records of 484 bytes
2022-04-14 15:44:23.936 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/clients", incoming x-last-modified=ServerTimestamp(1649987064360)
2022-04-14 15:44:23.936 32565-32601/org.mozilla.fenix.debug D/sync15::request: Committed batch NoBatch
2022-04-14 15:44:23.937 32565-32601/org.mozilla.fenix.debug I/sync15::clients::engine: Upload success (1 records success, 0 records failed)
2022-04-14 15:44:23.937 32565-32601/org.mozilla.fenix.debug I/sync15::clients::engine: Finished syncing clients
2022-04-14 15:44:23.937 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Synchronizing engines



2022-04-14 15:44:23.938 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing tabs engine!
2022-04-14 15:44:23.938 32565-32601/org.mozilla.fenix.debug I/sync15::sync: Syncing collection tabs
2022-04-14 15:44:23.938 32565-32601/org.mozilla.fenix.debug I/sync15::coll_state: Resetting tabs engine
2022-04-14 15:44:24.078 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/tabs", incoming x-last-modified=ServerTimestamp(1649987040780)
2022-04-14 15:44:24.079 32565-32601/org.mozilla.fenix.debug I/sync15::sync: Downloaded 8 remote changes (request 0 of 1)
2022-04-14 15:44:24.079 32565-32601/org.mozilla.fenix.debug I/sync15::sync: Uploading 1 outgoing changes
2022-04-14 15:44:24.080 32565-32601/org.mozilla.fenix.debug I/sync15::request: Posting 1 records of 1314 bytes
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/tabs", incoming x-last-modified=ServerTimestamp(1649987064630)
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug D/sync15::request: Committed batch NoBatch
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync15::sync: Upload success (1 records success, 0 records failed)
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/tabs::sync::engine: sync completed after uploading 1 records


2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync15::sync: Sync finished!
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Sync of tabs was successful!
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync15::sync_multiple: Finished syncing engines.
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug D/sync15::sync_multiple: sync was successful, final status=Ok
2022-04-14 15:44:24.212 32565-32601/org.mozilla.fenix.debug I/sync_manager::manager: Sync finished with status Ok
2022-04-14 15:44:24.213 32565-32601/org.mozilla.fenix.debug I/sync_manager::manager: engine "tabs" status: Ok(())
2022-04-14 15:44:24.216 32565-32601/org.mozilla.fenix.debug I/SyncWorker: Successfully synced tabs
2022-04-14 15:44:24.225 32565-32668/org.mozilla.fenix.debug I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=940b97ff-0572-40bb-9978-b3a52f066fba, tags={ Immediate, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Common } ]
2022-04-14 15:44:24.230 32565-32590/org.mozilla.fenix.debug I/libglean_ffi: glean_core::ping: Collecting tabs-sync
2022-04-14 15:44:24.235 32565-32565/org.mozilla.fenix.debug D/LeakCanary: Watching instance of androidx.work.impl.background.systemjob.SystemJobService (androidx.work.impl.background.systemjob.SystemJobService received Service#onDestroy() callback) with key 5bf768f5-591f-41cd-9393-2f397e53ea8a
2022-04-14 15:44:24.237 32565-32590/org.mozilla.fenix.debug I/libglean_ffi: glean_core::upload::directory: Processing ping at: /data/user/0/org.mozilla.fenix.debug/glean_data/pending_pings/5a0c81e5-3dd1-446b-a3cf-9ed18dd9a4fd
2022-04-14 15:44:24.237 32565-32590/org.mozilla.fenix.debug I/libglean_ffi: glean_core: The ping 'tabs-sync' was submitted and will be sent as soon as possible
2022-04-14 15:44:24.238 32565-32590/org.mozilla.fenix.debug I/libglean_ffi: glean_core::ping: Collecting sync
```

While I feel it's too early to tell. I think it gives some credence to potentially somewhere SyncManager is thinking places needs to be synced when in fact we only want the tabs engine? Figured I add this finding for now but will dive in more on this.

**Comment by skhamis** [comment] 2022-04-16 01:24
Last look-in for the week. I added some additional logs to see where the discrepancy is happening and some interesting finds....

I've annotated `[MY ADDITIONAL LOG]` to areas I've added additional logs too. So looks like a-c is properly only wanting to sync the tabs engine via this log

```
2022-04-15 14:55:03.412 17559-23252/org.mozilla.fenix.debug D/SyncWorker: Starting sync... Tagged as: [Immediate, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Common]
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_new
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/tabs: tabs_14ee_TabsStore_register_with_sync_manager

[MY ADDITIONAL LOG]
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/SyncWorker: Sync Params set, syncing Some(engines=[tabs])

2022-04-15 14:55:03.425 17559-23252/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_sync
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-15 14:55:03.428 17559-23252/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered
```

As you can see, immediately after we get the `no PlacesApi` registered. Which is correct, because fenix only wanted to sync tabs at the time and thus never properly registered the places_api. NOTE: This could be happening for other engines too but only Places has this error in the `None` match:
https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/places/src/api/places_api.rs#L46-L48


Best I can tell, the issue starts from this call here: https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/sync_manager/src/manager.rs#L200

 which calls: https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/sync_manager/src/manager.rs#L186-L187

and lastly: https://github.com/mozilla/application-services/blob/363c2b6bdb5f134f14c623063939e54f56045db2/components/sync_manager/src/manager.rs#L32-L41

Right now it's _trying_ to get every engine here regardless if only a tabs was requested (even if it doesn't use it later). So most of them silently return `None` but as linked above, places will throw that error. So there's two potentially fixes: 

1. Leverage SyncParams and instead only grabbed necessary engines
2. Don't log that error there (not ideal)


Full logs below (with annotations) 
```
2022-04-15 14:55:02.668 17559-23255/org.mozilla.fenix.debug D/SyncWorker: Starting sync... Tagged as: [mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common]
2022-04-15 14:55:02.670 17559-17642/org.mozilla.fenix.debug I/WM-WorkerWrapper: Worker result SUCCESS for Work [ id=989a8581-71e4-41e7-9476-3568b3ce410b, tags={ mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Debounce, Common } ]
2022-04-15 14:55:02.675 17559-17559/org.mozilla.fenix.debug D/LeakCanary: Watching instance of androidx.work.impl.background.systemjob.SystemJobService (androidx.work.impl.background.systemjob.SystemJobService received Service#onDestroy() callback) with key 98718d94-85a6-425d-b1e0-5d8dba17ce0e
2022-04-15 14:55:03.376 17559-23250/org.mozilla.fenix.debug D/tabs: tabs_14ee_TabsStore_set_local_tabs
2022-04-15 14:55:03.377 17559-17559/org.mozilla.fenix.debug D/SyncedTabsStorage: SyncedTabsStorage called, syncing TabsOnly!!!
2022-04-15 14:55:03.378 17559-23250/org.mozilla.fenix.debug I/FirefoxAccount: Executing: get access token
2022-04-15 14:55:03.378 17559-23250/org.mozilla.fenix.debug D/fxa_client: fxa_client_907c_FirefoxAccount_get_access_token
2022-04-15 14:55:03.379 17559-23250/org.mozilla.fenix.debug D/fxa_client: fxa_client_907c_FirefoxAccount_to_json
2022-04-15 14:55:03.379 17559-23250/org.mozilla.fenix.debug D/WrappingPersistenceCallback: Logging state to mozilla.components.service.fxa.StorageWrapper$PersistenceCallback@b03bdd3
2022-04-15 14:55:03.379 17559-23250/org.mozilla.fenix.debug D/FxaStatePersistenceCallback: Persisting account state into mozilla.components.service.fxa.SecureAbove22AccountStorage@29eb74c
2022-04-15 14:55:03.387 17559-23250/org.mozilla.fenix.debug I/FirefoxAccount: Successfully executed: get access token
2022-04-15 14:55:03.387 17559-23250/org.mozilla.fenix.debug I/FirefoxAccount: Executing: getTokenServerEndpointURL

2022-04-15 14:55:03.388 17559-23250/org.mozilla.fenix.debug D/fxa_client: fxa_client_907c_FirefoxAccount_get_token_server_endpoint_url
2022-04-15 14:55:03.388 17559-23250/org.mozilla.fenix.debug I/FirefoxAccount: Successfully executed: getTokenServerEndpointURL

[MY ADDITIONAL LOG]
2022-04-15 14:55:03.388 17559-17701/org.mozilla.fenix.debug D/FirefoxAccountStateMachine: FxAccountManager.syncnow called, syncing [mozilla.components.service.fxa.SyncEngine$Tabs@24066a9]

[MY ADDITIONAL LOG]
2022-04-15 14:55:03.388 17559-17701/org.mozilla.fenix.debug D/BgSyncManager: SyncManager.now called, syncing [mozilla.components.service.fxa.SyncEngine$Tabs@24066a9]

2022-04-15 14:55:03.388 17559-17701/org.mozilla.fenix.debug D/WMSyncDispatcher: Immediate sync requested, reason = mozilla.components.service.fxa.sync.SyncReason$User@a3f39a7, debounce = false

[MY ADDITIONAL LOG]
2022-04-15 14:55:03.388 17559-17701/org.mozilla.fenix.debug D/WMSyncDispatcher: WorkManager.syncNow called, syncing [mozilla.components.service.fxa.SyncEngine$Tabs@24066a9]

2022-04-15 14:55:03.412 17559-23252/org.mozilla.fenix.debug D/SyncWorker: Starting sync... Tagged as: [Immediate, mozilla.components.service.fxa.sync.WorkManagerSyncWorker, Common]
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_new
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/tabs: tabs_14ee_TabsStore_register_with_sync_manager


[MY ADDITIONAL LOG]
2022-04-15 14:55:03.417 17559-23252/org.mozilla.fenix.debug D/SyncWorker: Sync Params set, syncing Some(engines=[tabs])
2022-04-15 14:55:03.425 17559-23252/org.mozilla.fenix.debug D/sync_manager: syncmanager_88ca_SyncManager_sync

[ACTUAL ERROR]
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered
2022-04-15 14:55:03.427 17559-23252/org.mozilla.fenix.debug I/mozac/CrashReporter: Caught Exception report submitted to 1 services
2022-04-15 14:55:03.428 17559-23252/org.mozilla.fenix.debug E/places::api::places_api: get_registered_sync_engine: no PlacesApi registered


2022-04-15 14:55:03.432 17559-23252/org.mozilla.fenix.debug D/sync_manager::manager: Not under backoff
2022-04-15 14:55:03.432 17559-23252/org.mozilla.fenix.debug I/sync_manager::manager: No backoff in effect (or we decided to ignore it), starting sync
2022-04-15 14:55:03.433 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing 1 engines
2022-04-15 14:55:03.433 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Loading/initializing persisted state
2022-04-15 14:55:03.433 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Preparing client info
2022-04-15 14:55:03.433 17559-23252/org.mozilla.fenix.debug D/sync15::sync_multiple: mem_cached_state was stale or missing, need setup
2022-04-15 14:55:03.440 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Entering sync state machine
2022-04-15 14:55:03.440 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Advancing state machine to ready (full)
2022-04-15 14:55:03.440 17559-23252/org.mozilla.fenix.debug D/sync15::token: Fetching token from https://token.services.mozilla.com/1.0/sync/1.5
2022-04-15 14:55:04.136 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/info/configuration", incoming x-last-modified=ServerTimestamp(0)
2022-04-15 14:55:04.239 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/info/collections", incoming x-last-modified=ServerTimestamp(1650070235350)
2022-04-15 14:55:04.334 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/meta/global", incoming x-last-modified=ServerTimestamp(1649980347780)
2022-04-15 14:55:04.334 17559-23252/org.mozilla.fenix.debug D/sync15::client: Got meta global with modified = 1649980347.78; last-modified = 1649980347.78
2022-04-15 14:55:04.334 17559-23252/org.mozilla.fenix.debug I/sync15::state: Have info/collections and meta/global. Computing new engine states


2022-04-15 14:55:04.334 17559-23252/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: input EngineStateInput { local_declined: {"passwords", "prefs", "addons"}, remote: Some(RemoteEngineState { info_collections: {"clients", "crypto", "meta", "history", "tabs", "bookmarks", "forms"}, declined: {"passwords", "addons", "prefs"} }), user_changes: {} }
2022-04-15 14:55:04.334 17559-23252/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: output EngineStateOutput { declined: {"prefs", "addons", "passwords"}, changes_needed: EngineChangesNeeded { local_resets: {}, remote_wipes: {} } }
2022-04-15 14:55:04.436 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/crypto/keys", incoming x-last-modified=ServerTimestamp(1646340669080)
2022-04-15 14:55:04.436 17559-23252/org.mozilla.fenix.debug D/sync15::sync_multiple: Declined engines list after state machine set to: Some(["prefs", "addons", "passwords"])
2022-04-15 14:55:04.436 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Synchronizing clients engine
2022-04-15 14:55:04.436 17559-23252/org.mozilla.fenix.debug I/sync15::clients::engine: Syncing collection clients
2022-04-15 14:55:04.546 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/clients", incoming x-last-modified=ServerTimestamp(1650070235120)
2022-04-15 14:55:04.546 17559-23252/org.mozilla.fenix.debug D/sync15::clients::engine: Found my record on the server
2022-04-15 14:55:04.546 17559-23252/org.mozilla.fenix.debug D/sync15::clients::engine: Will update our client record on the server
2022-04-15 14:55:04.546 17559-23252/org.mozilla.fenix.debug I/sync15::request: Posting 1 records of 484 bytes
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/clients", incoming x-last-modified=ServerTimestamp(1650070505160)
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug D/sync15::request: Committed batch NoBatch
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::clients::engine: Upload success (1 records success, 0 records failed)
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::clients::engine: Finished syncing clients
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Synchronizing engines
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing tabs engine!
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::sync: Syncing collection tabs
2022-04-15 14:55:04.694 17559-23252/org.mozilla.fenix.debug I/sync15::coll_state: Resetting tabs engine
2022-04-15 14:55:04.806 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/tabs", incoming x-last-modified=ServerTimestamp(1650070235350)
2022-04-15 14:55:04.806 17559-23252/org.mozilla.fenix.debug I/sync15::sync: Downloaded 8 remote changes (request 0 of 1)
2022-04-15 14:55:04.806 17559-23252/org.mozilla.fenix.debug I/sync15::sync: Uploading 1 outgoing changes
2022-04-15 14:55:04.806 17559-23252/org.mozilla.fenix.debug I/sync15::request: Posting 1 records of 1570 bytes
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/193499625/storage/tabs", incoming x-last-modified=ServerTimestamp(1650070505410)
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug D/sync15::request: Committed batch NoBatch
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/sync15::sync: Upload success (1 records success, 0 records failed)
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/tabs::sync::engine: sync completed after uploading 1 records
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/sync15::sync: Sync finished!
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Sync of tabs was successful!
2022-04-15 14:55:04.935 17559-23252/org.mozilla.fenix.debug I/sync15::sync_multiple: Finished syncing engines.
2022-04-15 14:55:04.936 17559-23252/org.mozilla.fenix.debug D/sync15::sync_multiple: sync was successful, final status=Ok
2022-04-15 14:55:04.936 17559-23252/org.mozilla.fenix.debug I/sync_manager::manager: Sync finished with status Ok
2022-04-15 14:55:04.936 17559-23252/org.mozilla.fenix.debug I/sync_manager::manager: engine "tabs" status: Ok(())
2022-04-15 14:55:04.937 17559-23252/org.mozilla.fenix.debug I/SyncWorker: Successfully synced tabs
```

**Closed** 2022-04-20 20:31 UTC
