### ISSUE TITLE
Implement a way to gather "snapshot" metrics

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#2127] opened 2019-11-08 00:04 UTC
https://github.com/mozilla/application-services/issues/1749#issuecomment-547726334 distinguishes between two types of metrics:

* "Event-based", emitted for actions like changing a username or password. These are a good fit for a `counter` with `lifetime: ping`, or even event telemetry.
* "Snapshot", like the number of saved logins, or a histogram for `timeLastUsed`. (For example, 5 passwords were used in the last day, 10 in the last 5 days, 25 in the last 3 weeks, and so on).

Event-based metrics are easy to collect, and fit well into the Glean model. We'd call `add` or `record`, and Glean would take care of accumulating and sending them.

Snapshot metrics are harder. Let's use "number of saved passwords" as an example.

First, we'll need to figure out when to collect them. https://github.com/mozilla/application-services/issues/1749#issuecomment-547758197 mentions the `gather-telemetry` notification on Desktop, which is unreliable and not guaranteed to run before a ping is sent. Since we're already accessing the database, we might be able to do this on every logins write (add, remove, update, sync), or on a call to `get_all`.

However, I think we also want a "once a day" failsafe, so that we can send at least one ping with the number of saved logins in a day, even if the user doesn't interact with their logins. We can build that ourselves, but having to duplicate that across all our components isn't ideal.

It would be handy if Glean could notify us somehow, like "I'm going to send a ping soon, now would be a good time to collect any snapshot telemetry." There are issues there with callbacks over FFI, and I don't know what we'd do if the telemetry gathering step was async, so that might not work.

Second, it's not clear what metric type we should use for them. Just skimming the Glean docs:

* `type: quantity` looks exactly like what we're looking for, but the [docs say](https://mozilla.github.io/glean/book/user/metrics/quantity.html) it's only meant for Gecko metrics.
* Can we define it as a `lifetime: application` metric, and set it at startup? I don't think so. A user might add and remove logins as they interact with the app, and waiting until the app is restarted means we'll record stale values. Considering we want to measure the value of the logins component, stale values would be really unfortunate.
* Can we use `type: counter`, record an initial value at app startup (or when the logins component is first accessed), and increment the counter each time a login is added? Nope. Counters can only be incremented, not decremented, so we can't subtract from the total count when a login is deleted. And, Glean resets the counter to 0 when it submits the ping, meaning we'll lose the total we had before.

@Dexterp37, I'd love your input on this! :smile:

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-648)

**Comment by linacambridge** [comment] 2019-11-08 00:16
IIUC, on Desktop, we'd use `Services.telemetry.scalarAdd` for event-based metrics, and `scalarSet` for snapshots.

**Comment by Dexterp37** [comment] 2019-11-08 09:04
> 
> 
> [#1749 (comment)](https://github.com/mozilla/application-services/issues/1749#issuecomment-547726334) distinguishes between two types of metrics:
> 
>     * "Event-based", emitted for actions like changing a username or password. These are a good fit for a `counter` with `lifetime: ping`, or even event telemetry.
> 
>     * "Snapshot", like the number of saved logins, or a histogram for `timeLastUsed`. (For example, 5 passwords were used in the last day, 10 in the last 5 days, 25 in the last 3 weeks, and so on).
> 
> 
> Event-based metrics are easy to collect, and fit well into the Glean model. We'd call `add` or `record`, and Glean would take care of accumulating and sending them.

Just to make sure I understand correctly: by "event-based" metrics you don't really mean just [`events`](https://mozilla.github.io/glean/book/user/metrics/event.html), but any metric for which the value is not a constant, right?

And "snapshot" metrics are kind of constant values?

> Snapshot metrics are harder. Let's use "number of saved passwords" as an example.
> 
> First, we'll need to figure out when to collect them. [#1749 (comment)](https://github.com/mozilla/application-services/issues/1749#issuecomment-547758197) mentions the `gather-telemetry` notification on Desktop, which is unreliable and not guaranteed to run before a ping is sent. Since we're already accessing the database, we might be able to do this on every logins write (add, remove, update, sync), or on a call to `get_all`.

As you mentioned, the `gather-telemetry` model is unreliable (I would say broken by design) and not meant to be used anymore, even on desktop.

The Glean model addresses addresses this slightly differently: developers are in control of the [metric's lifetime](https://mozilla.github.io/glean/book/user/metric-parameters.html#optional-metric-parameters), can define the pings they go into and also manage pings schedule.

_Example_ : for the "number of saved passwords", we could create a metric with `lifetime: ping` (or `lifetime: application`), and set its value whever a password is added or removed. Whatever value is in there will be picked up when a ping is sent.

I'm not sure We need to rely on a signal "hey, I need to collect telemetry because I want to send a ping" for this case. Am I missing something here?

> However, I think we also want a "once a day" failsafe, so that we can send at least one ping with the number of saved logins in a day, even if the user doesn't interact with their logins. We can build that ourselves, but having to duplicate that across all our components isn't ideal.

Glean already offers a "once a day" ping out of the box. Unless you were *really* motivated to deal with all the scheduling nonsense that comes with a custom "once per day scheduling" mechanism, I'd strongly encourage to put metrics in our [`metrics` ping](https://mozilla.github.io/glean/book/user/pings/metrics.html).

> It would be handy if Glean could notify us somehow, like "I'm going to send a ping soon, now would be a good time to collect any snapshot telemetry." There are issues there with callbacks over FFI, and I don't know what we'd do if the telemetry gathering step was async, so that might not work.

Unfortunately, this would break the Glean "push-only" principle :) If there's a specific use-case that it's hard to serve with the combination of metric lifetime and custom pings, then we should probably discuss about it and see what to design to make it work! I suspect that a signal like that (which reminds me of `gather-telemetry` a lot) would never be an answer :-P We've been biten by this too much in Firefox.

> Second, it's not clear what metric type we should use for them. Just skimming the Glean docs:
> 
>     * `type: quantity` looks exactly like what we're looking for, but the [docs say](https://mozilla.github.io/glean/book/user/metrics/quantity.html) it's only meant for Gecko metrics.

We're always open to talking about current metric types: if some use-case doesn't fit the tools we provide, we can change them or create new ones!

We are currently figuring an open process to do this, as the Glean SDK team should not be the gatekeeper for new types. We should have a panel that includes various stakeholders (the team who requested the type, data science, glean pipeline, glean SDK, data stewards) and evaluate additions/changes.

Yours seems like a good case to either unlock the `Quantity` metric type for all uses or slightly tweak the `Counter` to allow decrements.

>     * Can we define it as a `lifetime: application` metric, and set it at startup? I don't think so. A user might add and remove logins as they interact with the app, and waiting until the app is restarted means we'll record stale values. Considering we want to measure the value of the logins component, stale values would be really unfortunate.

With `Quantity`, we could set the current number of saved logins whenever that number changes. The latest value would get into the ping(s).

>     * Can we use `type: counter`, record an initial value at app startup (or when the logins component is first accessed), and increment the counter each time a login is added? Nope. Counters can only be incremented, not decremented, so we can't subtract from the total count when a login is deleted. And, Glean resets the counter to 0 when it submits the ping, meaning we'll lose the total we had before.

If we were to allow decrements, we could set an initial count when logins component is first accessed and then increment/decrement when some login action happens.

The Glean SDK resets values only for `lifetime: ping` metrics when the ping metrics are in is sent (regardless of the metric type). If the count needs to live as long as the application live, the `lifetime: application` would give the behaviour you desire (i.e. value not cleared after the ping is sent).

What do you think?

**Comment by linacambridge** [comment] 2019-11-11 23:04
Thank you as always, @Dexterp37!

> Just to make sure I understand correctly: by "event-based" metrics you don't really mean just events, but any metric for which the value is not a constant, right?
>
> And "snapshot" metrics are kind of constant values?

Yep, exactly!

> Example : for the "number of saved passwords", we could create a metric with `lifetime: ping` (or `lifetime: application`), and set its value whever a password is added or removed. Whatever value is in there will be picked up when a ping is sent.

We could definitely do that! It shouldn't be too expensive for logins, but I'm worried it'll be more costly in other cases. For example, if we want to count the number of saved bookmarks or history pages, and the user has a lot of them, running a `COUNT(*)` to update the quantity in telemetry on every `History.insert` or `Bookmarks.insert` call is going to add up. We'd also like to send those quantities at least once a day, even if the user doesn't add or remove any items.

IOW, we'd like to make sure the (potentially expensive) collection logic runs at least once in a measurement window, so that it can be included in the next ping. Does that make sense?

On a side note, are `lifetime: application` metrics sent when the app is foregrounded, or only when it restarts? If we want to send the number of saved passwords as a quantity, every day, but the user goes a few days without quitting and relaunching Fenix (or Desktop)...does that mean we might not record the metric then?

> We're always open to talking about current metric types: if some use-case doesn't fit the tools we provide, we can change them or create new ones!

That's fantastic to hear! 😄

> With `Quantity`, we could set the current number of saved logins whenever that number changes. The latest value would get into the ping(s).

That's exactly what we're looking for! 😊

**Comment by Dexterp37** [comment] 2019-11-12 10:06
> > Example : for the "number of saved passwords", we could create a metric with `lifetime: ping` (or `lifetime: application`), and set its value whever a password is added or removed. Whatever value is in there will be picked up when a ping is sent.
> 
> We could definitely do that! It shouldn't be too expensive for logins, but I'm worried it'll be more costly in other cases. For example, if we want to count the number of saved bookmarks or history pages, and the user has a lot of them, running a `COUNT(*)` to update the quantity in telemetry on every `History.insert` or `Bookmarks.insert` call is going to add up.

If we would add support for decrementing `Counter` types in the Glean SDK, or create a new type that allows decrements, you could do something like that:

- After the first sync or startup, we add the number of history entries to the Glean `HistoryItemsCounter` (this is the place where `COUNT(*)` would happen, right?).
- When `History.insert` is called, we call `HistoryItemsCounter.add(1)` (no `COUNT(*)` takes place here).
- When `History.remove` is called, we call `HistoryItemsCounter.subtract(1)` (no `COUNT(*)` takes place here) - **Note** we do not currently support `subtract`, this would need to be discussed.

> We'd also like to send those quantities at least once a day, even if the user doesn't add or remove any items.

That's not a problem at all: you can either add the metrics to _both_ your `sync` ping (sent at your own controlled scheduled) and the Glean SDK `metrics` ping (which has the guaranteed behaviour of being sent once per day, if Fenix was opened).

If you **really** want to deal with scheduling your own ping once per day (trust me on this, it's _very tricky_ on mobile), nothing prevents you from defining a new ping in `pings.yaml`, add your metrics to it and send it once per day :)

> IOW, we'd like to make sure the (potentially expensive) collection logic runs at least once in a measurement window, so that it can be included in the next ping. Does that make sense?

I'm afraid this is an hard thing to guarantee, unless you use a custom ping for which you control the schedule :) This option would mean:

- defining a new ping, e.g. `sync-heavy` (or add that to the current sync pings);
- add any potentially expensive data to that ping;
- once you've finished collecting all the heavy/expensive things send your ping.

This is the only way to _guarantee_.

> On a side note, are `lifetime: application` metrics sent when the app is foregrounded, or only when it restarts? If we want to send the number of saved passwords as a quantity, every day, but the user goes a few days without quitting and relaunching Fenix (or Desktop)...does that mean we might not record the metric then?

The lifetime of a metric [does not have to do](https://mozilla.github.io/glean/book/user/metric-parameters.html#optional-metric-parameters) with when it is **sent**. It has to do with **when is the contained data cleared**.

- Do we clear the data after restarting the application? (= `lifetime: application`, _example_: the OS name, which can be set once when the application starts and remains the same throughout the application lifetime, it never gets reset when a ping is sent)
- Do we clear the data after the ping containing the metric is sent? (= `lifetime: ping`, _example_: how many searches were performed before this ping was sent?)
- Do we clear the data only when the application is uninstalled? (= `lifetime: user`, _example_: think of the client id)

@linacambridge , does the above make sense?

It's also interesting to note that the Glean SDK supports multi-store by default: you can define a metric once and it can go in different pings. If the metric has `lifetime: ping`, this basically means you have one metric storage per ping, being cleared when the related ping is sent.
 
> > With `Quantity`, we could set the current number of saved logins whenever that number changes. The latest value would get into the ping(s).
> 
> That's exactly what we're looking for! 😊

I thought that too, but given the above details both options seem to be interesting :)

**Comment by rfk** [comment] 2019-11-20 06:02
One interesting wrinkle on the `Quantity`-type metrics discussed above, which I realized in writing out https://github.com/mozilla/application-services/pull/2225: reporting an accurate count of number of logins or number of bookmarks might risk reducing anonymity for sync users, because we can get a good sense of which users have how many items by inspecting their data stored on the sync server. Users with a unique logins count might become uniquely identifiable in telemetry pings!

I wonder if we might need some kind of "quantized quantity" metric in this case (which desktop currently achieves using a histogram that gets cleared on each use).

**Comment by Dexterp37** [comment] 2019-11-20 09:22
> 
> 
> One interesting wrinkle on the `Quantity`-type metrics discussed above, which I realized in writing out #2225: reporting an accurate count of number of logins or number of bookmarks might risk reducing anonymity for sync users, because we can get a good sense of which users have how many items by inspecting their data stored on the sync server. Users with a unique logins count might become uniquely identifiable in telemetry pings!

This is a really interesting point! It might be worth bringing Data Stewardship in for this specific thing. @chutten what do you think of this (or can you flag somebody else who might have opinions?)?

> I wonder if we might need some kind of "quantized quantity" metric in this case (which desktop currently achieves using a histogram that gets cleared on each use).

Maybe, yes, it could be a legitimate use case. @rfk when you say "cleared on each use", what do you mean?

**Comment by chutten** [comment] 2019-11-20 15:44
Wow, this is a trip. Defending one of our own systems against fingerprinting another of our own systems is a relatively new concept, so the layers of precedents and procedures are too thin for me to fall back on. For example, there have been times in the past where we've reduced the resolution of timestamps, but that was defence against timing attacks.

I have a lot of Thoughts, Feelings, and Opinions about this that I think would be best shared in a less-public area first. I'll follow-up with @rfk offline.

**Comment by rfk** [comment] 2019-11-21 05:47
> when you say "cleared on each use", what do you mean?

Every time the telemetry-gathering code on desktop fires, it grabs a reference to the `PWMGR_NUM_SAVED_LOGINS`, histogram, clears any previous data, and writes a single datapoint giving the current number of saved logins: 
* https://dxr.mozilla.org/mozilla-central/rev/01032a31b2e2a094281035a8a191d00ec8d5958c/toolkit/components/passwordmgr/LoginManager.jsm#172

**Comment by Dexterp37** [comment] 2019-11-21 06:22
> 
> 
> > when you say "cleared on each use", what do you mean?
> 
> Every time the telemetry-gathering code on desktop fires, it grabs a reference to the `PWMGR_NUM_SAVED_LOGINS`, histogram, clears any previous data, and writes a single datapoint giving the current number of saved logins:
> 
>     * https://dxr.mozilla.org/mozilla-central/rev/01032a31b2e2a094281035a8a191d00ec8d5958c/toolkit/components/passwordmgr/LoginManager.jsm#172

As stated in the other comments, I'm afraid that would violate the Glean "push only" principle :(
Would counting logins [as shown in this comment](https://github.com/mozilla/application-services/issues/2127#issuecomment-552824385) fit the usecase? If not, why? (I'm trying to better understand this)

**Comment by rfk** [comment] 2019-11-21 07:48
> Would counting logins as shown in this comment fit the usecase?

Yes, I think this counter-style would work. I don't think we need to try to copy the histogram-cleared-on-each-use approach from desktop, just using it to explain by analogy.

**Comment by chutten** [comment] 2019-11-28 20:09
That makes these probes fairly ancient. We functionally deprecated "gather-telemetry" before I even joined Mozilla : )

Official word from Trust is we can proceed with caution in reporting counts of items stored in sync servers while we consider tech and policy for keeping the fingerprinting risk low. Maybe keep them on six-month expiry windows to start with? That way as we evolve our doctrine around this we can update the collection to match.

**Comment by rfk** [comment] 2020-02-13 05:47
There's a lot of good discussion here (thanks all!) but I think this bug is not very actionable as-is. We've shipped the initial version of the logins metrics without this, and when we cycle back to revisiting them, it seems likely that we'll be better served by starting a fresh bug and taking a fresh look at the problem. I'm going to close this out.

**Closed by rfk** 2020-02-13 05:47 UTC
