### ISSUE TITLE
Android sync data choices not synchronized on iOS

### ISSUE THREAD

**Issue by vasilicatamas** [mozilla/application-services#2605] opened 2020-02-07 15:20 UTC
**Build:**
Stage [Train 1.157.0]

**Affected platforms:**
Android 9
iOS 13.1.2

**Steps to reproduce:**
1.Connect on both Android and iOS devices using the same Firefox account.
2.Edit Sync Preferences on Android.
3.Trigger a Sync on Android.
4.Trigger a Sync on iOS.

**Expected results:**
Android edited sync preferences are successfully synced on iOS

**Actual Results:**
Sync preferences are not synchronized on iOS and they are reversed to the previous state on Android.

┆Issue is synchronized with this [Jira Bug](https://jira.mozilla.com/browse/SYNC-800)
┆Sprint: Backlog

**Comment by data-sync-user** [comment] 2020-02-20 12:47
➤ Janet Dragojevic commented:

[~vtamas@mozilla.com] - is this reproducible for you with Fenix + iOS as well?

**Comment by vasilicatamas** [comment] 2020-04-03 14:23
> [~[vtamas@mozilla.com](mailto:vtamas@mozilla.com)] - is this reproducible for you with Fenix + iOS as well?

@jdragojevic I was unable to reproduce this issue with Fenix + iOS

**Comment by rfk** [comment] 2020-04-07 03:17
I recently found a related bug with handling sync data choices on iOS, where the iOS device re-applies its local changes on every sync:

  https://github.com/mozilla-mobile/firefox-ios/issues/6350

I don't *think* it can explain the behaviour in the video here, since the data choices seem to revert back to their previous state without syncing the iOS device. But perhaps Fennec has a similar issue with resolving local vs remote changes.

Unfortunately, given that the issue appears to be a Fennec client-side bug, I don't think we're likely to be able to ship a fix for this. I propose we close this as `WONTFIX` since the issue does not reproduce with Fenix.

**Closed by rfk** 2020-04-07 03:17 UTC
