### ISSUE TITLE
Jira mangles inline code formatting in github issues/comments

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2647] opened 2020-02-13 06:06 UTC
STR:

* Create an issue in Github, and use the single-backtick inline-code-snippet syntax to carefully describe something (like `this`).
* Marvel briefly at how nice your carefully-crafted comment looks in Github.
* Wait for Jira to sync it over, and then view it in Jira.

Expected results:

* Observe that the nice carefully-crafted comment remains intact in Jira.

Actual results:

* Observe that the inline code snippet has now somehow become a block-formatted code snippet (like
`this`
) which breaks the flow of the comment and is generally quite jarring.

How will we know when we're done:

* When Jira renders the two "like this" examples in this as the text describes them, rather than mangling the first so it looks like the second.
* When [this existing example issue](https://jira.mozilla.com/browse/SYNC-790) becomes legible with inline code snippets intact.

(I'm sure I've seen Jira actually export is mangled snippets back to github in the past, but I couldn't find an example of that in a quick search just now, so maybe I imagined it).

---
(I'm editing the bug to see if Jira will sync new content and fix the formatting.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-828)

**Comment by data-sync-user** [comment] 2020-02-13 20:58
➤ Janet Dragojevic commented:

[~mlonglade@mozilla.com] or [~vdoan@mozilla.com] - Would either of you know if this is a Jira or a unito thing?

**Comment by data-sync-user** [comment] 2020-02-13 21:20
➤ Vien Doan commented:

Hi [~jdragojevic@mozilla.com] - I don't know but I asked Unito since they'll probably know. I'll let you know what I hear back. Thanks

**Comment by data-sync-user** [comment] 2020-02-13 23:41
➤ Vien Doan commented:

[~jdragojevic@mozilla.com] - Unito came back and confirmed that they can replicate the issue and pass on their engineers to fix. Let me try to get an estimated timeline. Thanks for your patience.

**Comment by data-sync-user** [comment] 2020-02-14 02:58
➤ Majken Longlade commented:

It looks like Jira doesn't support inline code snippet. Though it does allow inline preformatted text (like this). I would image that if Unito is able to fix this, that they would be translating the inline code markup from GitHub into preformatted text in Jira.

**Comment by data-sync-user** [comment] 2020-02-20 17:57
➤ Vien Doan commented:

[~jdragojevic@mozilla.com] I heard back from Unito and here is their response. 
{quote}Wanted to let you know that the codeblock formatting translation bug has now been fixed!
{quote}
I took a quick look and it looks like it has been fixed now also.

Thanks!

**Closed** 2020-02-24 20:27 UTC
