### ISSUE TITLE
Implement sync on desktop

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#2035] opened 2019-10-24 18:53 UTC
This largely is implementing the algorithm/algorithms for sync and conflict resolution described in the remerge spec.

It also requires implementing vector clocks and the like, if that's not done as part of local storage.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-26)
┆Story Points: 5
┆Epic: chrome.sync.storage (Generic Sync) prototype

**Comment by jdragojevic** [comment] 2020-01-08 21:59
Duplicate of 2036 - closing

**Closed by jdragojevic** 2020-01-08 21:59 UTC
