### ISSUE TITLE
Expose content server URLs to customers

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#305] opened 2018-10-18 18:16 UTC
Motivation: The Reference Browser wants to construct the `{content_server_base}/connect_another_device?showSuccessMessage=true` URL to navigate to it once the user is logged-in.

I do not want them to build the URL themselves, and also would like to own the `connect_another_device?showSuccessMessage=true` part completely otherwise future migrations will prove difficult.

`Config` is an owned struct by `FirefoxAccount` so we can't really call methods on it once it has been consumed in the `FirefoxAccount` constructor.
This is not ideal, but let's add a `get_[...]_url` method that constructs that URL for us the same way `get_token_server_endpoint_url` does and expose this function in the FFI crate.
Note that in the future these URL "builders" will probably multiply, and we'll need to find a better way to expose them.

Bonus objective: Add a `Config::latest()` method and expose it within the FFI crate as I think the Android team uses that.

cc @csadilek

**Comment by rfk** [comment] 2018-10-22 03:19
> Config is an owned struct by FirefoxAccount so we can't really call methods on it once it has been
> consumed in the FirefoxAccount constructor.

Could we have some sort of `get_config()` method that returns a borrowed reference to the config?  Otherwise it seems like these `get_xyz_url` methods could easily proliferate into an unmanageable state.

**Comment by mhammond** [comment] 2018-11-13 22:45
Dupe of #303

**Closed by mhammond** 2018-11-13 22:45 UTC
Labels: next
