### ISSUE TITLE
Are iOS users getting disconnect from Sync?

### ISSUE THREAD

**Issue by davismtl** [mozilla/application-services#2160] opened 2019-11-13 19:36 UTC
I suspect users may slowly be getting disconnected from FxA/Sync on Firefox for iOS.

It’s happened to @clouserw and me in the somewhat recent past.

We see a steady decrease of MAU in our numbers. This bug was about data science investigating it:
https://bugzilla.mozilla.org/show_bug.cgi?id=1589414

This was me requesting that we surface better UI when someone does get disconnected:
https://github.com/mozilla-mobile/firefox-ios/issues/5722

But fundamentally, if we have to internal reports of users getting disconnected and our numbers are going down, we may already need to start investigating on the engineering side.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-357)
┆Epic: important not urgent

**Comment by eoger** [comment] 2019-11-13 19:39
It happened to me too, I noticed I got put into the "reconnect to Sync" state after 2 weeks of usage of Firefox for iOS.

**Comment by davismtl** [comment] 2019-11-14 00:38
When I shared this bug with Ashley Thomas and Keith Willowhawk, Keith said that he also experiences regular disconnects.

**Comment by athomasmoz** [comment] 2019-11-18 21:45
Thanks for taking this on! Let me know if you need support on the FF iOS side, sounds like this is affecting a large number of our FxA users.

**Comment by rfk** [comment] 2019-11-18 23:07
In https://github.com/mozilla-mobile/firefox-ios/issues/5722#issuecomment-555241360, it looks like Alex's device managed to put itself in the "disconnected" state, but still had a valid entry in the FxA "devices and apps" list on the web.  For other folks on here who also see the same problem, it would be great if you can confirm whether you see similar behaviour:

1. Notice that you've been disconnected in Firefox for iOS, with the app settings screen showing the "Enter your password to connect" messaging.
1. Visit https://accounts.firefox.com/settings/clients inside Firefox for iOS.  Are you able to access the page immediately, or does it as you to sign in again? Do you see an entry in the list that corresponds to your iOS device?
1. Visit https://accounts.firefox.com/settings/clients in another browser. Do you see an entry in the list that corresponds to your iOS device?

**Comment by rfk** [comment] 2019-11-18 23:12
This is going to be hard to debug unless we're able to reliably reproduce, or can work out the bug from first principles. Here are my notes from poking around at the code:

* The "Enter your password to connect" messaging is shown when `profile.getAccount().actionNeeded` is `.needsPassword`.  As far as I can tell this corresponds uniquely to the FxA state-machine being in the "separated" state. So these devices appear to be driving themselves to the "separated" state, somehow.
* There's a `profile.getAccount().makeSeparated()` method which will drive the state-machine to this state, but I can only find a single non-debugging-related place where it gets called: in response to a `401` from the tokenserver.
  * I feel like there *should* be other ways to get to `separated`, e.g. by trying and failing to refresh the BrowserID certificate. But I can't easily find any.

So one possibility here is that we're getting a recoverable error from the tokenserver, but treating it as fatal, and driving to the "separated" state when we don't need to.  If that were the case though, it seems like a bug that we will have had for a very long time.

@davismtl do you have a sense of how recently this issue may have started? From the linked bugs it sounds like maybe quite a recent thing.

**Comment by rfk** [comment] 2019-11-18 23:32
> I feel like there should be other ways to get to separated, e.g. by trying and failing to refresh the BrowserID certificate

I found this one, it's [here](https://github.com/mozilla-mobile/firefox-ios/blob/9741a9ec05728f161818c233ae4aab760344f459/Account/FxALoginStateMachine.swift#L102), along with a couple of other branches that transition to "separated" in response to unexpected errors.

**Comment by rfk** [comment] 2019-11-19 02:06
I filed a couple of bugs for places where the iOS FxA integration might be incorrectly driving users to the "separated" state: https://github.com/mozilla-mobile/firefox-ios/issues/5776, https://github.com/mozilla-mobile/firefox-ios/issues/5777.

However, both of these have been in the product for years, so I don't think they're enough to explain a sudden increase in users getting disconnected from sync.

**Comment by davismtl** [comment] 2019-11-19 16:09
> @davismtl do you have a sense of how recently this issue may have started? From the linked bugs it sounds like maybe quite a recent thing.

The drop in DAU (and MAU) seems to have really started somewhere between July 8th and 15th. July 8th is FxA train 140, July 10th is the release Firefox for iOS 18.1 and July 15th aligns with FxA train 141.

https://analytics.amplitude.com/mozilla-corp/chart/10dr6w5/edit/nea84js

**Comment by rfk** [comment] 2019-11-19 19:25
For anyone who encounters this again, Garvan shared these instructions for obtaining log files from the app, please try to do so are share with the team for debugging:

""'
The user should be able to tap the version number in settings 5x, which enables debug settings, one of which is "Debug: copy log files to app container". Then if the connect to a mac, open iTunes and select the Firefox iOS app, it will show the log file for the app, which can then be copied to the computer.
"""

**Comment by st3fan** [comment] 2019-11-20 15:24
@davismtl are you able to share your logs with @rfk ?

**Comment by davismtl** [comment] 2019-11-21 00:18
I'll share them with him but from what I can tell, I only have 4 days of logs.

**Comment by rfk** [comment] 2019-11-21 01:34
Unfortunately I don't think these contained anything related to the disconnection event, but let's keep an eye out for it happening again and be sure to grab logs if it does.

**Comment by vladikoff** [comment] 2019-11-21 20:56
We've done some investigation with the iOS team and haven't found anything just yet. (the stable.dev server is throwing some 502 errors which seems unrelated to this)

**Comment by rfk** [comment] 2019-12-18 03:26
@grigoryk reports hitting this today.

**Comment by davismtl** [comment] 2019-12-19 21:27
@grigoryk any log files 🤞?

**Comment by eoger** [comment] 2020-01-29 09:46
I finally may have figured what is happening here, my Firefox iOS got disconnected after taking a flight to the Berlin all hands.
Checked the logs, sure enough here's the state machine transitioning to the Separated state:
```
2020-01-27 19:30:24.976 [Info] [FxALoginStateMachine.swift:51] advanceOne(fromState:now:) > Advancing from state: married
2020-01-27 19:30:24.976 [Debug] [FxALoginStateMachine.swift:55] advanceOne(fromState:now:) > Checking key pair freshness.
2020-01-27 19:30:24.976 [Debug] [FxALoginStateMachine.swift:60] advanceOne(fromState:now:) > Checking certificate freshness.
2020-01-27 19:30:24.976 [Info] [FxALoginStateMachine.swift:62] advanceOne(fromState:now:) > Certificate has expired; transitioning to CohabitingAfterKeyPair.
2020-01-27 19:30:24.976 [Info] [FxALoginStateMachine.swift:51] advanceOne(fromState:now:) > Advancing from state: cohabitingAfterKeyPair
2020-01-27 19:30:24.976 [Debug] [FxALoginStateMachine.swift:86] advanceOne(fromState:now:) > Signing public key.
2020-01-27 19:30:25.008 [Error] [FxALoginStateMachine.swift:119] advanceOne(fromState:now:) > Unknown error: <FxAClientError.Local Error Domain=org.mozilla.fxa.error Code=999 "Invalid server response">.  Transitioning to Separated.
```
[
Here's the line in question](https://github.com/mozilla-mobile/firefox-ios/blob/b861f7d78f70fe658d80be8cb1e08f5459e582c4/Account/FxALoginStateMachine.swift#L119) where we transition to `Separated`.
The handled error [is generated by `makeRequest`](https://github.com/mozilla-mobile/firefox-ios/blob/b861f7d78f70fe658d80be8cb1e08f5459e582c4/Account/FxAClient10.swift#L648-L681).

I believe this might be a fallout from https://github.com/mozilla-mobile/firefox-ios/pull/5014 which changed the way Firefox iOS makes HTTP requests, and I'm guessing the emitted errors when a network request fails are different.
As for triggering the error, possibly a captive portal (commonly found in airports and planes) triggered the problem?

My suggestion would be to not be as eager to transition to `Separated` in FxALoginStateMachine if a local error is being handled, or alternatively rework `makeRequest` to emit different error kinds. 

cc @garvankeeley

**Comment by garvankeeley** [comment] 2020-01-30 13:54
> I believe this might be a fallout from [mozilla-mobile/firefox-ios#5014](https://github.com/mozilla-mobile/firefox-ios/pull/5014) which changed the way Firefox iOS makes HTTP requests, and I'm guessing the emitted errors when a network request fails are different.

Prior to that patch, HTTP requests used a wrapper lib `Alamofire`, of which were weren't using any feature of it that wouldn't be available through `URLSession`. The patch attempted to keep the logic the exact same, including error handling, but probably there is a mistake there. I'll take a look.

**Comment by garvankeeley** [comment] 2020-02-10 17:20
Issue/Fix on Firefox iOS side: https://github.com/mozilla-mobile/firefox-ios/pull/6086

**Comment by rfk** [comment] 2020-02-13 05:48
Sounds like we can safely close this, thanks all!

**Closed by rfk** 2020-02-13 05:48 UTC
