### ISSUE TITLE
places_bookmarks_import_from_fennec: Unexpected error: MergeError(Error(Cycle(Guid...

### ISSUE THREAD

**Issue by vladikoff** [mozilla/application-services#3412] opened 2020-07-28 21:10 UTC
Reference: https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9257398/events/cea5418189f54230b9ff26a7256ca841/
![image](https://user-images.githubusercontent.com/128755/88722446-3e5bf400-d0f5-11ea-84ae-03f4a53aa309.png)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1538)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by linacambridge** [comment] 2020-07-28 22:16
I think this is a dupe of #2725—Dogear won't break cycles yet.

**Comment by grigoryk** [comment] 2020-07-29 17:24
@linacambridge I see you've through through that issue, do you think this is something we can land reasonably soon to help with the release migration?

**Comment by linacambridge** [comment] 2020-07-30 00:35
@grigoryk Hmm, no, I think we decided not to land cycle breaking earlier to avoid risks to migration. Has that changed?

**Comment by data-sync-user** [comment] 2021-01-25 21:36
➤ Janet Dragojevic commented:

Since we're well past migration - going to close this one as a wontfix.

**Closed by data-sync-user** 2021-01-25 21:36 UTC
