### ISSUE TITLE
[Blocker] Firefox iOS is unable to embed & sign Application Services v69.0.0 framework to iTunesConnect

### ISSUE THREAD

**Issue by nbhasin2** [mozilla/application-services#3877] opened 2021-02-19 22:21 UTC
Does anyone know if we need to embed & sign this or embed without signing?
Locally I can build this on phone and on sim but this issue is specific to uploading release build to iTunes Connect.

Marked as a blocker as if we need to embed the binary we'll have to resolve these items before uploading new Firefox iOS build to iTunesConnect

Error details: cc @rfk 

```1 package(s) were not uploaded because they had problems:
/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/B1FCF8B6-2F6B-41B5-B82E-320DA4864DF9/989804926.itmsp - Error Messages:
ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Client.app/Frameworks/MozillaAppServices.framework/sdk_generator.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
ERROR ITMS-90087: "Unsupported Architectures. The executable for Client.app/Frameworks/MozillaAppServices.framework contains unsupported architectures '[x86_64]'."
ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker."
2021-02-19 21:45:43.020 altool[10503:98469] *** Error: Error uploading '/Users/vagrant/deploy/Firefox.ipa'.
2021-02-19 21:45:43.020 altool[10503:98469] *** Error: code -18000 (ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Client.app/Frameworks/MozillaAppServices.framework/sdk_generator.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html")
2021-02-19 21:45:43.020 altool[10503:98469] *** Error: code -18000 (ERROR ITMS-90087: "Unsupported Architectures. The executable for Client.app/Frameworks/MozillaAppServices.framework contains unsupported architectures '[x86_64]'.")
2021-02-19 21:45:43.020 altool[10503:98469] *** Error: code -18000 (ERROR ITMS-90125: "The binary is invalid. The encryption info in the LC_ENCRYPTION_INFO load command is either missing or invalid, or the binary is already encrypted. This binary does not seem to have been built with Apple's linker.")```

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2066)
┆Epic: a-s consumer issues
┆Sprint: SYNC - 2021-02-26

**Comment by rfk** [comment] 2021-02-21 23:45
Hrm, I'm well out of my depth here but am happy to help muddle through. Is this something I would be able to reproduce locally with the right build commands?

A couple of unordered thoughts while I do a bit of poking at this:

* In the previous static-linking setup, I guess we didn't have this problem - you were pulling the code directly into your own frameworks and so it would necessarily be covered by the code signature on those frameworks.
* I don't see any logic in the appservices build process that tries to codesign the resulting artifacts, which also makes me think that our default expectation was for the app to handle this.
* On the other hand, other external dependencies like "SwiftProtobuf" and "SwiftyJSON" seem to be configured as "Do Not Embed", and it's not obvious to me why we should want to handle AppServices differently.

I suspect that "embed & sign" is going to be the shortest path to success.

> ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Client.app/Frameworks/MozillaAppServices.framework/sdk_generator.sh] is not properly signed. [...]

If this script in particular is causing problems, I wonder if we can avoid bundling it. You need to run it as part of the app build process but there's no reason it needs to be included in the final app bundle. (Although I don't know how to exclude it in practice).

> ERROR ITMS-90087: "Unsupported Architectures. The executable for Client.app/Frameworks/MozillaAppServices.framework contains unsupported architectures '[x86_64]'."

Indeed it does contain that, IIUC for simulator builds. An SO post [here](https://stackoverflow.com/questions/30547283/submit-to-app-store-issues-unsupported-architecture-x86) suggests some ways to strip the unsupported architecture during the build process but it doesn't feel right that we'd have to do that.

That post also suggests something about `carthage copy-frameworks` - I wonder if it would make a difference if we treated `MozillaAppServices` in the same manner as e.g. `SwiftProtobuf.framework`, adding it to the "copy carthage dependencies" build phase rather than the apps' own "copy frameworks" phase? (I don't have a good mental model for what that phase *does*, I just note that other dependencies are treated differently).

**Comment by rfk** [comment] 2021-02-22 00:08
> I wonder if it would make a difference if we treated MozillaAppServices in the same manner as e.g. SwiftProtobuf.framework,
> adding it to the "copy carthage dependencies" build phase rather than the apps' own "copy frameworks" phase?
> (I don't have a good mental model for what that phase does, I just note that other dependencies are treated differently).

FWIW I tried building the app like this (move appservices into "copy carthage dependencies", diff [here](https://github.com/mozilla-mobile/firefox-ios/compare/main...rfk:appservices-copy-carthage?expand=1) for reference) and the app seemed to build and run successfully in the simulator. I don't know if it would make a difference with publishing to the store, but could be worth a try.

**Comment by nbhasin2** [comment] 2021-02-22 23:30
I believe this is progress and we are down to just one error cc @rfk 

```
Package Summary:
 
1 package(s) were not uploaded because they had problems:
	/var/folders/6q/wgy6jtp12w5gzgm9lzcglpqw0000gn/T/4A94C145-3DF6-49CB-9E39-C47BC1D162F7/989804926.itmsp - Error Messages:
		ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Client.app/Frameworks/MozillaAppServices.framework/sdk_generator.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html"
2021-02-22 23:27:58.402 altool[10518:98886] *** Error: Error uploading '/Users/vagrant/deploy/Firefox.ipa'.
2021-02-22 23:27:58.403 altool[10518:98886] *** Error: code -18000 (ERROR ITMS-90035: "Invalid Signature. Code object is not signed at all. The file at path [Client.app/Frameworks/MozillaAppServices.framework/sdk_generator.sh] is not properly signed. Make sure you have signed your application with a distribution certificate, not an ad hoc certificate or a development certificate. Verify that the code signing settings in Xcode are correct at the target level (which override any values at the project level). Additionally, make sure the bundle you are uploading was built using a Release target in Xcode, not a Simulator target. If you are certain your code signing settings are correct, choose "Clean All" in Xcode, delete the "build" directory in the Finder, and rebuild your release target. For more information, please consult https://developer.apple.com/library/ios/documentation/Security/Conceptual/CodeSigningGuide/Introduction/Introduction.html")
[31;1mUploading IPA failed: exit status 1[0m
```

**Comment by rfk** [comment] 2021-02-22 23:35
So, this `sdk_generator.sh` script. It originates in Glean, and I believe we do need to ship it as part of `MozillaAppServices.framework`, because `firefox-ios` needs to run it in one of its build phases. You probably want to continue to use the version shipped via appservices, so that you can get future updates to this script from Glean.

I wonder if there is a way to delete it from the copied bundle after `carthage copy-frameworks` has done its thing?

**Comment by data-sync-user** [comment] 2021-02-23 18:30
➤ Janet Dragojevic commented:

Based on the slack conversation https://mozilla.slack.com/archives/CKL0LGV9B/p1614051057023700 ( https://mozilla.slack.com/archives/CKL0LGV9B/p1614051057023700 ) , I believe this issue is resolved.  Is there any further work required here before closing?

**Comment by nbhasin2** [comment] 2021-02-23 18:35
Janet, we can close this as Firefox iOS has had successful last few builds with A~S v69.0.0 and is no longer a blocker.
Thanks again for all the help!

**Closed** 2021-02-24 15:37 UTC
