### ISSUE TITLE
FxAccountManager has no func to get settings URL

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#2634] opened 2020-02-12 14:47 UTC
It would make sense to get this from the manager (would be consistent with getting the login URL from the manager).

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-820)

**Comment by eoger** [comment] 2020-02-12 14:57
Duplicate of https://github.com/mozilla/application-services/issues/2563.

**Closed by eoger** 2020-02-12 14:57 UTC
