### ISSUE TITLE
Discuss whether to serialize the entire RemoteConfig as part of the account object

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#2468] opened 2020-01-13 19:48 UTC
In https://github.com/mozilla/application-services/pull/2465, both @eoger and myself were caught off guard by the fact that the `FirefoxAccount` object serializes the entire `RemoteConfig` as part of its internal state. Let's discuss whether this is the right factoring, or whether that data should be stored separately or perhaps not at all, and instead looked up on demand.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-737)

**Comment by eoger** [comment] 2020-04-21 21:51
Duplicate of #2998.

**Closed by eoger** 2020-04-21 21:51 UTC
