### ISSUE TITLE
Maintain a list of key-bearing scopes, to remove 'wantsKeys' from the auth API

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1399] opened 2019-07-11 23:39 UTC
See relevant A-C bug: https://github.com/mozilla-mobile/android-components/issues/3747

It makes more sense to maintain this list somewhere here rather than in A-C.

**Comment by eoger** [comment] 2019-07-11 23:40
Duplicate of https://github.com/mozilla/application-services/issues/1400.

**Closed by eoger** 2019-07-11 23:40 UTC
Labels: 🗝 FxA
