### ISSUE TITLE
Add a way for us to trigger CI runs from comments on PRs

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#1168] opened 2019-05-22 19:44 UTC
Specifically, not having this makes it painful to deal with external contributions.

Additionally, for frequent contributors (bots as a concrete example), it would be nice if someone with read access to the repo would have things run in taskcluster.

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-41)

**Comment by eoger** [comment] 2019-05-22 19:48
See also https://github.com/mozilla/application-services/issues/1138

**Comment by eoger** [comment] 2019-07-17 15:29
Duplicate of https://github.com/mozilla/application-services/issues/1299.

**Closed by eoger** 2019-07-17 15:29 UTC
Labels: 📈technical investment
