### ISSUE TITLE
Sending tabs can cause backoff errors

### ISSUE THREAD

**Issue by bendk** [mozilla/application-services#5918] opened 2023-11-14 15:21 UTC
We currently have a decent amount of [HTTP backoff errors](https://mozilla.sentry.io/discover/results/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=fxa-client-other-error%3A+No+stored+session+token&project=6295546&query=issue%3AFENIX-NIGHTLY-7BZ+back+off&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29) reporting in Sentry.

I looked through a handful of these errors and it seems like most of them are caused by clients trying to send too many tabs to other devices.  Is there a way to avoid backoff errors in this case?

- We could rate limit it in the firefox UI.  If a user tries to send too many tabs, they get an error message.  This doesn't seem great, but it's probably better than silently failing, which I believe is what's currently happening.
- Could we batch these somehow?
   - Giving the user a checklist of tabs could be nice.
  - We could also batch things behind the scenes, like after you send 5 tabs in a short period of time, we assume you're bulk sending your tabs.  At that point we start delaying the push notifications so that we can queue up multiple requests and send them all at once.

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-4010)

**Comment by mhammond** [comment] 2023-11-14 21:19
Basically a dupe of https://bugzilla.mozilla.org/show_bug.cgi?id=1817329 - tl;dr - we know beforehand that this error is going to be raised based on the number of tabs, so it's really dumb for us to offer UI which we know with certainty is never going to work.

**Comment by mhammond** [comment] 2023-11-24 15:31
Moved to bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1866541

Change performed by the [Move to Bugzilla add-on](https://addons.mozilla.org/en-US/firefox/addon/move-to-bugzilla/).

**Closed by mhammond** 2023-11-24 15:31 UTC
