### ISSUE TITLE
Create a seperate "focus-ios" megazord for focus

### ISSUE THREAD

**Issue by tarikeshaq** [mozilla/application-services#4821] opened 2022-02-03 19:43 UTC
After the [91.0.1](https://github.com/mozilla/rust-components-swift/releases/tag/91.0.1) release of `rust-components-swift` all the components are released as one target. Meaning that Focus iOS now will start getting the swift code for components it's not interested in (i.e fxa, sync, etc).  For now that shouldn't be a problem, the code is not consumed by Focus anyways - and they already load the full Rust binary anyways.

However, a clear optimization for this is to create a separate megazord for focus, one that only includes the libraries they need, then import that in `rust-components-swift` as a different target than the one we ship for Firefox iOS.

This would include:
- creating a new crate inside `megazords`, and have that crate similarly structured to [`megazords/ios-rust`](https://github.com/mozilla/application-services/tree/main/megazords/ios-rust), except in it's `Cargo.toml` it only includes the components focus uses
- Generalize the [`build-xcframework`](https://github.com/mozilla/application-services/blob/main/megazords/ios-rust/build-xcframework.sh) script to build the two separate frameworks (probably move it outside the `ios-rust` and rename `ios-rust` to `firefox-ios`
- [Change our CircleCI release job](https://github.com/mozilla/application-services/blob/main/.circleci/config.yml#L447-L457) to release both frameworks
- In `rust-components-swift`:
   - Import the new framework as a **new** binary target
   - update our `generate` script to pull in all the relevant code into a different directory than the one firefox ios consumes
   - Create a new swift target, that consumes that binary target
   - Create a new library representing that target that we ship
   
 Proably two mid-sized tickets - one for appservices and one for rust-components-swift. But let's hold off of this until the dust settles and both consumers are consuming the library with no errors

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-3045)

**Comment by data-sync-user** [comment] 2022-04-28 21:15
➤ Tarik Eshaq commented:

duplicate of https://mozilla-hub.atlassian.net/browse/SYNC-3156 ( https://mozilla-hub.atlassian.net/browse/SYNC-3156|smart-link )

**Closed** 2022-05-11 19:26 UTC
Labels: discuss
