### ISSUE TITLE
Password change doesn't immediately trigger Rust calls FxaUnauthorizedException

### ISSUE THREAD

**Issue by BranescuMihai** [mozilla/application-services#3348] opened 2020-07-14 08:20 UTC
After user changed password on Desktop, every rust call done from mobile should get an `FxaUnauthorizedException`, so that the user re-authenticates. 

However, after password change, there is usually a ~10 seconds window(doesn't happen every time) in which performing a call to get all devices from Mozilla Android Components (`LibFxAFFI.INSTANCE.fxa_get_devices(this.handle.get(), ignoreCacheArg, e)`) returns the devices even though password is changed, and the call to get all remote tabs (`LibRemoteTabsFFI.INSTANCE.remote_tabs_get_all(this.handle.get(), error)`) sometimes returns only local tabs, and sometimes returns also the remote ones, even in those 10 seconds.

This leads to unwanted states in Fenix during that time-window. I wonder if this is an architectural decision(eventual consistency) and it should be handled by the client, or this is a problem.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1484)
┆Story Points: 3
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-07-31

**Comment by rfk** [comment] 2020-07-15 03:12
Thanks for reporting this. There are some architectural reasons why one might see eventual consistency here, but I believe they're mostly historical. It used to be that oauth refresh tokens lived in a separate system to the main account data, and the "password change" event had to propagate from one system to the other via a message queue. But I just checked in the code and that's not true anymore.

So I'm not sure how to explain this. @dannycoates, can you think of a reason why a refreshToken might remain valid for ~10 seconds after the user changes their account password?

**Comment by dannycoates** [comment] 2020-07-17 00:40
> can you think of a reason why a refreshToken might remain valid for ~10 seconds after the user changes their account password?

I can't from a brief look at the code. It might help to see some request logs.

**Comment by rfk** [comment] 2020-07-17 00:41
From triage today, @vladikoff said he'd see if he could reproduce.

**Comment by vladikoff** [comment] 2020-07-21 14:45
**This does not reproduce:**

if I am in the Sync screen and press "Sync Now", I am instantly kicked out after password change.
if I am in the Syncd tabs view and swipe to refresh, I am instantly kicked out after password change.

**This sort of reproduces with the Share Tab / Send Tab menu:**

<img src=https://user-images.githubusercontent.com/128755/88069193-26a5ce00-cb3f-11ea-84e0-ef463857ed78.png width=150 /> It could be due to some caching done by the Share Menu. @BranescuMihai is that what you were seeing?

**Comment by vladikoff** [comment] 2020-07-21 15:38
Okay I was able to reproduce this behaviour with this branch: https://github.com/mozilla/application-services/tree/password-change-slow

STR:

* Checkout the `password-change-slow` branch
* Run ` cargo run --example fxa-devices-api   ` 
* Follow the steps to login
* Open FxA web settings, change password
* The script will get device info after password change for about 10-20+ seconds

(You need to `rm credentials.json` after you change the password to try again)

**Comment by vladikoff** [comment] 2020-07-22 00:45
From further investigation, it seems like the debouncing logic in Rust components is causing this.

**Closed** 2020-07-28 02:39 UTC
