### ISSUE TITLE
Possibly incorrect handling of the declined list

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#3205] opened 2020-06-04 22:07 UTC
See https://github.com/mozilla-mobile/android-components/issues/7233#issuecomment-639141014 for details.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1377)
┆Story Points: 5
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-06-19

**Comment by mhammond** [comment] 2020-06-05 01:49
As Ryan noticed, there's `06-04 14:38:09.826 10608 10729 E sync15::sync_multiple: Failed to parse PersistedGlobalState from JSON! Falling back to default` in the log, so I suspect we actually have 2 bugs here:

* whatever that is!
* the fact that we treat that state as meaning there's nothing declined - we should certainly be treating that as a first-sync where we trust the remote.

Something else odd in that log is:

> 06-04 14:38:09.170 10608 10649 I sync15::coll_state: Resetting passwords store
> 06-04 14:38:09.173 10608 10649 I logins::db: Executing reset on password store!
> 06-04 14:38:09.173 10608 10649 D logins::db: Updating last sync to 0

And I can't see any evidence that's expected.

**Comment by mhammond** [comment] 2020-06-10 08:27
Some updates:

`Failed to parse PersistedGlobalState from JSON! Falling back to default` is logged for both invalid state and no state - the latter is expected in the first sync for a user - so this is a red herring (and I've a local fix to that)

For reasons I don't understand, the first sync appears to be *two* syncs in quick succession:

> 2020-06-10 17:46:42.805 14296-14426/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing 4 stores
> <snip expected JSON error above>
> 2020-06-10 17:46:44.264 14296-14426/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: input EngineStateInput { local_declined: {}, remote: Some(RemoteEngineState { info_collections: {"crypto", "prefs", "passwords", "addresses", "extension-storage", "clients", "bookmarks", "addons", "meta", "tabs"}, declined: {"history", "forms"} }), user_changes: {} }
> 2020-06-10 17:46:44.265 14296-14426/org.mozilla.fenix.debug D/sync15::state: compute_engine_states: output EngineStateOutput { declined: {"forms", "history"}, changes_needed: EngineChangesNeeded { local_resets: {"history", "forms"}, remote_wipes: {} } }

So we've done the right thing (so far :)

> 2020-06-10 17:46:51.495 14296-14426/org.mozilla.fenix.debug D/sync15::sync_multiple: Sync result: SyncResult { service_status: Ok, declined: Some(["forms", "history"]), result: Ok(()), engine_results: {"passwords": Ok(()), "bookmarks": Ok(()), "tabs": Ok(())}, telemetry: SyncTelemetryPing { version: 1, uid: Some("0fc91048cf12d45647d8ec784d60526c"), events: [], syncs: [SyncTelemetry { when_took: Finished(WhenTook { when: 1591775205.0, took: 6443 }), engines: [Engine { name: "bookmarks", when_took: Finished(WhenTook { when: 1591775205.0, took: 5465 }), incoming: Some(EngineIncoming { applied: 3234, failed: 0, new_failed: 0, reconciled: 0 }), outgoing: [EngineOutgoing { sent: 4, failed: 0 }], failure: None, validation: Some(Validation { version: 0, problems: [], failure: None }) }, Engine { name: "passwords", when_took: Finished(WhenTook { when: 1591775210.0, took: 419 }), incoming: Some(EngineIncoming { applied: 19, failed: 0, new_failed: 0, reconciled: 0 }), outgoing: [EngineOutgoing { sent: 0, failed: 0 }], failure: None, validation: None }, Engine { name: "tabs", when_took: Finished(WhenTook { when: 1591775210.0, took: 557 }), incoming: Some(EngineIncoming { applied: 0, failed: 0, new_failed: 0, reconciled: 0 }), outgoing: [EngineOutgoing { sent: 1, failed: 0 }], failure: None, validation: None }], failure: None }] }, next_sync_after: None }

This all looks good - then:
> 2020-06-10 17:46:51.565 14296-14343/org.mozilla.fenix.debug I/sync15::sync_multiple: Syncing 4 stores

So immediately a new sync has started - this seems odd - and we *also* see the "invalid json" message. That's not really expected here, but shouldn't cause harm. But then:

> 2020-06-10 17:46:51.565 14296-14343/org.mozilla.fenix.debug D/sync15::state: global state: "WithPreviousState"
> 2020-06-10 17:46:51.565 14296-14343/org.mozilla.fenix.debug D/sync15::client: request: GET /1.5/131779883/info/collections (None)
> 2020-06-10 17:46:51.815 14296-14343/org.mozilla.fenix.debug I/sync15::client: Successful request to "/1.5/131779883/info/collections", incoming x-last-modified=ServerTimestamp(1591775211720)
2020-06-10 17:46:51.815 14296-14343/org.mozilla.fenix.debug D/sync15::state: global state: "Ready"
> 2020-06-10 17:46:51.815 14296-14343/org.mozilla.fenix.debug W/sync15::sync_multiple: persisted state set to Some("{\"schema_version\":\"V2\",\"declined\":null}")

We've ended up with the wrong declined state! The problem is that we have a valid *memory* state, so we never [hit the code that re-calculates our declined state](https://github.com/mozilla/application-services/blob/4224a6f10df8711d6ec33fcb02a47fc3cccd53ca/components/sync15/src/state.rs#L407)

So this can be fixed either [here](https://github.com/mozilla/application-services/blob/4224a6f10df8711d6ec33fcb02a47fc3cccd53ca/components/sync15/src/state.rs#L516) by detecting we weren't passed the declined (we don't have a `PersistedGlobalState` there, so that might be non-trivial) or just do it in `sync_multiple.rs` and discard all memory state if we have no persisted state. The latter seems fine.

Then the broader question is: why does that second sync happen, and why doesn't it have state? (I'm guessing the answer to the second part is that the second sync started before the state from the first one was stashed)

I'm out of time tonight - I should get a PR up for the state thing tomorrow, but not clear I'll discover why the 2 syncs.

**Comment by mhammond** [comment] 2020-06-16 00:33
Calling this fixed by #3220 - there's still an android components issue regarding 2 syncs being done, but that shouldn't cause actual harm.

**Closed by mhammond** 2020-06-16 00:33 UTC
Labels: 🔄 Sync Manager
