### ISSUE TITLE
Monitor "fxa_configured" probe with sync decouple work

### ISSUE THREAD

**Issue by appsvc-moz** [mozilla/application-services#1896] opened 2019-09-27 19:00 UTC
Currently, the "fxa_configured" probe is working correctly. We should monitor the probe once we implement the sync decouple telemetry to make sure it reports the same data as today and to avoid regression.

---
🐞 Issue is synchronized with Bugzilla [Bug 1582253](https://bugzilla.mozilla.org/show_bug.cgi?id=1582253)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-236)

**Comment by rfk** [comment] 2019-12-06 06:59
Accidental dupe of https://github.com/mozilla/application-services/issues/1815, closing.

**Closed by rfk** 2019-12-06 06:59 UTC
Labels: bugzilla
