### ISSUE TITLE
Automatically respect server backoff and retry-after

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#1327] opened 2019-06-26 03:24 UTC
Both FxA and Sync define a simple server-driven backoff protocol to use when they're under heavy load; here's the FxA docs on the subject:

  https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/docs/api.md#back-off-protocol

We should invest in respecting this automatically - if the server has sent a `503` with `Retry-After: 30` in the header, we should refuse to issue new requests to that hostname for 30 seconds, and instead just return the same `503`.

I wonder if it makes sense to implement this by default inside viaduct, or whether that would involve too much state management behind-the-scenes for that lib. @mhammond @thomcc thoughts?

┆Issue is synchronized with this [Jira Story](https://jira.allizom.org/browse/SYNC-172)

**Comment by mhammond** [comment] 2019-06-26 05:10
The docs for the sync manager does mention this (and it will probably also need a "client initiated backoff" as done on desktop to avoid "failure loops"). However, that isn't going to handle FxA, as the interaction with FxA is currently outside the scope of the sync manager.

I'm sure Thom will have thoughts on doing it directly in viaduct, but at face-value that doesn't seem to be the right thing to do.

**Comment by mhammond** [comment] 2019-06-26 05:15
(Note also that I believe the intention is to have a user-initiated sync ignore the backoff request. Not clear how that would work in practice for the FxA portions, but that should be easy in the context of the sync manager design)

**Comment by mhammond** [comment] 2019-07-01 00:55
This is a dupe of #1216

**Closed by mhammond** 2019-07-01 00:55 UTC

**Comment by cse-test-sync** [comment] 2019-07-09 21:20
➤ Janet Dragojevic commented:

closing as a dup of Jira SYNC-127
