### ISSUE TITLE
CI fails to cross-compile win32 code in newer versions of Rust

### ISSUE THREAD

**Issue by thomcc** [mozilla/application-services#2245] opened 2019-11-20 21:24 UTC
Currently (as of #2171) we're pinned on 1.38.0, which isn't a position we would like to be in long term.

**Comment by eoger** [comment] 2019-11-20 21:33
Closing as this is a duplicate of https://github.com/mozilla/application-services/issues/2201.

**Closed by eoger** 2019-11-20 21:33 UTC
