### ISSUE TITLE
UrlParseFailed crashes in every single API which deals with urls

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#3536] opened 2020-08-25 19:39 UTC
We're seeing lots of UrlParseFailed coming out of every single API which deals with external URL input (history, bookmarks).

For history, a-c swallows some of these crashes already. However, they're not limited to things we can easily ignore. For example, this crash comes up when creating a bookmark: https://crash-stats.mozilla.org/report/index/35bb5d01-8cb9-4674-b20a-136530200825.
Ignoring a failure here isn't really a feasible approach. Surfacing an error to the user saying that we failed to create a bookmark for a website they have open in a tab, since its url is invalid is also not really an option.

Can we make url parsing more robust and/or more lenient?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1702)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-09-25

**Comment by eoger** [comment] 2020-08-25 19:54
It seems like we're hitting [this](https://searchfox.org/mozilla-mobile/rev/9cbb76f4bb290146a6f029dbd31b5affae2440cb/application-services/components/places/src/storage/bookmarks/public_node.rs#187-190), which would mean the database got populated with invalid urls (either through migration or just regular usage). Immediate action would be to ignore the error here, but maybe we should run a maintenance query that yanks invalid URLs and/or audit our URL inputs and figure out where the invalid URLs come from.

**Comment by rfk** [comment] 2020-08-25 22:42
Here's another one from a reddit thread: https://crash-stats.mozilla.org/report/index/cf7846b7-f131-49e5-9bc7-8ded60200825

**Comment by mhammond** [comment] 2020-08-26 04:07
This is a bit odd: both the fennec import process ([here](https://github.com/mozilla/application-services/blob/796e8c3a198f48919babca5abeda447f7cd70a4a/components/places/src/import/fennec/bookmarks.rs#L315) to [here](https://github.com/mozilla/application-services/blob/796e8c3a198f48919babca5abeda447f7cd70a4a/components/places/src/import/common.rs#L62)) and sync's handling of incoming records ([here](https://github.com/mozilla/application-services/blob/796e8c3a198f48919babca5abeda447f7cd70a4a/components/places/src/bookmark_sync/incoming.rs#L108) to [here](https://github.com/mozilla/application-services/blob/796e8c3a198f48919babca5abeda447f7cd70a4a/components/places/src/bookmark_sync/incoming.rs#L466)) both validate the URL in the same way these failing functions do (ie, `Url::parse()`). 

However, [this reddit thread](https://old.reddit.com/r/firefox/comments/igd8ah/firefox_crashes_when_i_type_mi_in_location_bar/) mentions that enabling sync is enough to make things crash again, which firmly implies Sync is allowing the bad URL through. A quick hack to the tests though show that Sync does what we expect here (which is ignore the incoming item and upload a tombstone for it) - so that's confounding.

Certainly if there's evidence of us rejecting an item that Fenix opens we have a different problem completely, but there's currently no evidence of that I can see and I heard a rumour that geckoview also uses the same rust url library we do. It's also impossible from a policy perspective, IIUC, to record these URLs in telemetry for privacy reasons - although maybe an exception is possible for scenarios like this? I wonder if we can have sentry and/or the crash reporter record whether sync is connected? That might help us understand this better.

It should be easy to make the search function Ed pointed at ignore the bad item, which I'll do, but that's not really a satisfactory resolution as I've still no real idea how we are ending up in this state.

**Comment by mhammond** [comment] 2020-08-27 01:50
https://sentry.prod.mozaws.net/operations/fenix-fennec/issues/9318285 is an issue calling `places_note_observation` with the failure being `places::ffi - URL parse error: invalid IPv4 address`. At face value, that seems like an example of "user is seeing the page but we are rejecting it as invalid".

I'm not totally convinced we should swallow this exception though - it should be easy for the app to swallow it, right? The fact we are getting it in sentry seems a feature we'd lose by having rust swallow it.

**Comment by mhammond** [comment] 2020-08-27 02:00
Actually, this is easily reproducible. In Fenix, ask to visit `http://1234.56.78.91` - Fenix will fail to display the page, but logcat will show the exact exception from the comment above (ie, it's trying to record it as a visit even though it's an error page). @grigoryk, that smells like a bug on your side of the fence, right?

**Comment by liuche** [comment] 2020-08-27 20:12
Since @grigoryk is on PTO for the next 2 weeks, is there someone else who could pick this up? Unless you mean this is on the AC side (rather than in app services)!

**Comment by rfk** [comment] 2020-08-27 21:40
> Unless you mean this is on the AC side

There's work for us on the appservices side, but the thing in mark's latest comment (logging visits to pages that fail to load) sounds like something to be dealt with in a-c. @liuche if we split that off into a separate a-c issue with clear steps to reproduce, does that sound reasonable?

**Comment by liuche** [comment] 2020-08-27 22:03
Yes, that sounds perfect!

**Comment by rfk** [comment] 2020-08-28 00:18
@mhammond are you happy to file the above a-c bug?

**Comment by mhammond** [comment] 2020-08-28 01:06
I filed https://github.com/mozilla-mobile/android-components/issues/8277 for history (that seems self-contained in a-c) and https://github.com/mozilla-mobile/fenix/issues/14331 for bookmarks (in the fenix repo as it seems likely that the fix for that will need to be in Fenix - but maybe that should be in a-c too)

**Comment by mhammond** [comment] 2020-09-02 03:40
https://github.com/mozilla/application-services/pull/3537 landed and I think that, plus https://github.com/mozilla-mobile/fenix/issues/14331 should have a large impact - please let us know when you'd like a new release of app-services cut (we could do it now, but might as well wait in case other bugs become ready before Fenix is)

**Comment by liuche** [comment] 2020-09-03 02:21
Sounds good! I'm trying to think if there are any other Sync bugs that we're waiting on, but not off the top of my head. If we don't hear of any, could we get an AS release for 9/11, so it can make it into the 9/15 AC release?

**Comment by mhammond** [comment] 2020-09-10 23:19
This was prematurely closed during triage. I don't think there's anything else actionable here other than the issues identified above, but I'll let @grigoryk and @liuche weigh in before closing.

**Closed** 2020-09-24 21:38 UTC
Labels: discuss
