### ISSUE TITLE
Logins API necessary for autofill: hostname lookup

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#1656] opened 2019-08-22 23:51 UTC
Currently we have no way to query logins storage by a hostname. The only way to do that is to slurp everything into memory (via `list()`), and do the filtering yourself. This means different clients may/will perform this slightly differently, and we're forcing them to perform this extra work.

This should be a storage API method instead.

**Comment by eoger** [comment] 2019-08-22 23:52
Duplicate of https://github.com/mozilla/application-services/issues/650.

**Closed by eoger** 2019-08-22 23:52 UTC
Labels: 🔐 Logins
