### ISSUE TITLE
lint-detekt tasks not showing up as completed

### ISSUE THREAD

**Issue by linacambridge** [mozilla/application-services#3051] opened 2020-04-29 04:24 UTC
For #3050 and #3042, the `lint-detekt` task was hanging indefinitely, so I had to merge the PRs manually. It looks like the tasks actually [do](https://firefox-ci-tc.services.mozilla.com/tasks/Ltw9_qX7RAGdGKV1__4d_g) [run](https://firefox-ci-tc.services.mozilla.com/tasks/Lcka6X0USDSl-O4jPJYvew) and finish, even though they show up as forever "pending" in the [GitHub](https://github.com/mozilla/application-services/pull/3050/checks?check_run_id=628364906) [UI](https://github.com/mozilla/application-services/pull/3042/checks?check_run_id=627256674)...I wonder if it's not reporting the status back or something?

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1196)
┆Sprint: Backlog

**Comment by eoger** [comment] 2020-04-29 14:31
Most likely a dupe of https://github.com/mozilla/application-services/issues/3004 (see https://bugzilla.mozilla.org/show_bug.cgi?id=1631099#c14)

**Closed** 2020-05-04 21:32 UTC
Labels: 🏭 Continuous Integration
