### ISSUE TITLE
[iOS] Receiving sent tab error: `JSON error invalid type: map, expected PushPayload`

### ISSUE THREAD

**Issue by garvankeeley** [mozilla/application-services#3145] opened 2020-05-22 14:48 UTC
x-ref https://github.com/mozilla-mobile/firefox-ios/issues/6671

Reports of this error receiving a sent tab. 
Error: https://user-images.githubusercontent.com/1866605/82678263-f67ea380-9c51-11ea-9c5b-82de6540f680.png

My concern is that I have not seen this reported before, it seems like something has changed on the backend.

A-S: v0.59.0

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1324)
┆Epic: a-s consumer issues
┆Sprint: SYNC - end 2020-06-05

**Comment by rfk** [comment] 2020-05-25 20:48
I don't think we've changed anything recently in the client code, but I wonder if this could be related to the recent changes in the autopush bridge server; /cc @eoger @jrconlin

**Comment by rfk** [comment] 2020-05-27 02:53
(Just noting bits of context as I think of them)

This `invalid type:` messaging is a serde error message, which IIUC means several things:
* The application successfully decrypted the push message contents and tried to hand it off to the FxA component
* The contents of the message were valid-enough JSON for serde to have a go at parsing it
* But the contents were not in the form expected by the fxa-client component

**Comment by garvankeeley** [comment] 2020-05-27 03:27
My 2 cents is that this message is a new thing, we are only seeing it recently, and client code is largely unchanged (as in there was no change I can recall that would correlate with this message now appearing). I can't discount the possibility that when I added more logging I covered a code path that wasn't covered previously, and thus the error started to show.

**Comment by rfk** [comment] 2020-05-27 03:34
I guess it could also be a new unexpected type of message being sent by the FxA server. Do we have e.g. sentry or other stats to tell us how often this error is happening?

**Comment by garvankeeley** [comment] 2020-05-27 04:05
It is on sentry https://sentry-fm.prod.mozaws.net/mozilla/firefox-ios-v250/?query=is%3Aunresolved+json, doesn't seem frequent.

**Comment by rfk** [comment] 2020-05-28 06:20
I wonder what the benefits vs risks would be of us returning (part of) the actual payload in that error message. It would probably help a great deal with debugging, but might risk sending PII to the logs, sentry, etc.

> v25.1 updated A-S to 0.58.3 from 0.58.0

Looking at the diff, that included and send-tab fixes from https://github.com/mozilla/application-services/pull/3101, but was otherwise a bunch of android and desktop stuff that shouldn't affect iOS.

I *think* all of those changes should have been downstream of the push stuff though - you need to successfully decrypt the push message before you can tell that it's a sent tab.

**Comment by rfk** [comment] 2020-05-28 06:41
The error message here is very specific and probably a good clue:

* `JSON error: invalid type: map, expected unit variant PushPayload::Unknown at line 1 column 105`

I tried passing a variety of junk data to the `handle_push_message` method to see what kinds of error message serde would produce. Results:

* `handle_push_message("{}")`
    * => ```missing field `command` at line 1 column 2```
* `handle_push_message("{\"command\": 42}")`
    * => ```invalid type: integer `42`, expected variant identifier at line 1 column 14```
* `handle_push_message("{\"command\": \"foo\"}")`
    * No error!
* `handle_push_message("{\"command\": \"foo\", \"data\": 42}")`
    * => ```invalid type: integer `42`, expected unit variant PushPayload::Unknown at line 1 column 29```
* `handle_push_message("{\"command\": \"foo\", \"data\": {}}")`
    * => ```invalid type: map, expected unit variant PushPayload::Unknown at line 1 column 29```

Aha! So I think the FxA server is sending us a value of "command" that we don't recognize, but serde's strict validation is failing because of the `data` field. This is a bug in appservices which I'll file separately, because from the code it looks like we *intend* to ignore unknown commands, but we don't in this case.

Now, why would we be getting a push with an unknown value for `command` and with a non-empty `data` field?  I don't know yet. The client code appears to have support for all the command strings known to the FxA server.

**Comment by rfk** [comment] 2020-05-28 06:56
Aha! It's possible for clients to send arbitrary "command" values via the `/devices/notify` endpoint, and we have a single use of that in current clients: [notifyCollectionChanged](https://searchfox.org/mozilla-central/source/services/sync/modules/engines/clients.js#616).

Let's see...

* `handle_push_message("{\"version\":1,\"command\":\"sync:collection_changed\",\"data\":{}}")`
  * => `invalid type: map, expected unit variant PushPayload::Unknown at line 1 column 58`

That's very close to the error message showing up in sentry. 

I bet a desktop device is trying to send you a tab via *old* send-tab, which used the sync clients collection and this `sync:collection_changed` push notification. If you've got someone who can reproduce this, see if they can watch in the Desktop Browser Console while sending a tab. I expect it would log something like `Sending a tab to ${client.name} using Sync.`

The FxA server has some logic to [allow sending the `sync:collection_changed` command to iOS](https://github.com/mozilla/fxa/blob/master/packages/fxa-auth-server/lib/push.js#L131). Do you still have the code in the iOS sync implementation to handle this message by checking for tabs sent via old-send-tab? If not, we'll need to figure out how to suppress it on the server.

**Comment by data-sync-user** [comment] 2020-05-28 07:47
➤ Ryan Kelly commented:

This wasn't in our current sprint, but I ended up down a bit of a rabbit-hole looking at this as part of broader "thinking about send-tab", so I'm moving it into "in progress" for completeness.

**Comment by eoger** [comment] 2020-06-02 17:17
We've made changes on the client and server side that should fix the problem.

**Closed by eoger** 2020-06-02 17:17 UTC
