### ISSUE TITLE
Push component should detect and recover from missing uaid

### ISSUE THREAD

**Issue by rfk** [mozilla/application-services#3751] opened 2020-12-09 07:06 UTC
It's possible for the autopush server to drop the current database record for a client, e.g. if it finds that there was some problem with the connection to Firebase Cloud Messaging. The expect behaviour in such cases is for the client to catch the "missing uaid" error from the server and re-create its records with a new uaid.

Our actual behaviour appears to be that we just [throw the "missing uaid" error](https://github.com/mozilla-services/autopush/issues/1445) and bail out, meaning we can't recover from such a state once we're in it.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1934)
┆Sprint: Backlog

**Comment by data-sync-user** [comment] 2020-12-11 06:00
➤ Ryan Kelly commented:

Turns out this is a dupe of https://jira.mozilla.com/browse/SYNC-1878

**Closed by data-sync-user** 2020-12-11 06:00 UTC
