### ISSUE TITLE
Report Sync/FxA errors

### ISSUE THREAD

**Issue by grigoryk** [mozilla/application-services#399] opened 2018-11-15 01:21 UTC
We'll need to inform users of errors that happen during syncing, and step one of that is to actually be aware of those errors. At a high level, there are multiple types of problems we'll encounter:
- requiring user attention and well defined (e.g. need to re-login)
- possibly requiring user attention and not well defined (e.g. we fail to sync a certain collection because we can't decrypt items in it...) 
- intermittent, outside of user control (service issues like 503s)
- intermittent, within user control (local network issues, "no connectivity", etc)

Some of these have clear recovery paths, some are "just try again later", some are "don't try until you fix this".

The more information we have a category of error we're encountering, the better chance we have of building a nice error/recovery UX.

**Comment by grigoryk** [comment] 2018-11-15 01:36
I think grouping various types of errors using "how will this be exposed to the user, if at all" as a guidance principle might help tackle this.

**Comment by mhammond** [comment] 2018-11-15 05:07
Desktop exposes only account related errors (ie, the `FxAError.Unauthorized` Ed mentioned). No other errors of any kind are exposed to the user - they were, but we removed them because they caused user anxiety and were almost never actionable by the user. I can't see any reason we'd want to expose more here.

**Comment by grigoryk** [comment] 2018-11-15 05:21
Mark, do we have somewhere I can read more about this? It’s always been my assumption in Fennec that we do a terrible job around reporting error states, things just “vaguely don’t work”. Even error states themselves are a bit flaky. Similar on iOS, lacklustre approach surfacing that something is going wrong caused a lot of user frustration.

I’m curious to read about the flip side and experience with this stuff on Desktop. How did we present errors, what kinds?

It feels like there must be a “golden middle” here where we empower users to fix problems as they come up, and get out of their hair for things they can’t affect.

**Comment by mhammond** [comment] 2018-11-15 06:00
https://bugzilla.mozilla.org/show_bug.cgi?id=979432 and https://bugzilla.mozilla.org/show_bug.cgi?id=1164475 are relevant.

There are loads of things that can go wrong - dns failures, network failures, http errors, ssl errors due to clock skew, etc. We might get DB errors from a corrupt places.db.  We might have "partial failures" for one engine (eg, somehow we got an invalid URL on the server.) We might have a repeating error for one engine but all others are working fine. Regardless, the only error a user can take action on is auth related.

I've no objection to ensuring errors get out to the caller, but it seems like alot of complexity for no identified gain. What errors would scheduling take into account? Desktop's scheduler cares about repeated failures to implement a backoff strategy, but (a) it doesn't matter what error and (b) that's never surfaced to the user.

IMO, telemetry is way more important than this - that's how to get actual insights into reliability.

**Comment by grigoryk** [comment] 2018-11-15 06:09
> I've no objection to ensuring errors get out to the caller, but it seems like alot of complexity for no identified gain. What errors would scheduling take into account? Desktop's scheduler cares about repeated failures to implement a backoff strategy, but (a) it doesn't matter what error and (b) that's never surfaced to the user.

That seems right. Auth errors need to be surfaced, some types of network errors - perhaps? On mobil users have a more immediate control over connectivity, but it's not clear we should be asking them to turn their network back on. Other errors can likely be silently consumed by whatever backoff/scheduling logic we'll have.

That sounds like two or three categories of errors. Perhaps we can start with that at the API boundary?

> IMO, telemetry is way more important than this - that's how to get actual insights into reliability.

Completely agree from reliability/quality pov. We still need _something_ here though.

**Comment by mhammond** [comment] 2018-11-15 06:14
FWIW, showing UI on network errors will almost certainly not be what you want as too many will be due to things like changing networks or other transient errors. Certainly the scheduler shouldn't schedule syncs when it knows there's no network.

>  We still need _something_ here though.

Genuine question: why? It sounds like an abstract concern - can you identify anything concrete?

**Comment by bug-mirror** [comment] 2019-04-29 22:33
@grigoryk what other errors would you like to see here?

**Comment by bug-mirror** [comment] 2019-04-29 22:34
from mtg: sync manager will change some of this

**Comment by jdragojevic** [comment] 2019-05-13 22:25
Closing as duplicate of https://github.com/mozilla-mobile/fenix/issues/2327.

Pls open specific bugs for any additional cases that are not documented there.

**Closed by jdragojevic** 2019-05-13 22:25 UTC
Labels: discuss, error-handling, ship-ready, ↕ Sync, 🗝 FxA
