### ISSUE TITLE
Update the vendored rusqlite in mozilla-central

### ISSUE THREAD

**Issue by eoger** [mozilla/application-services#3629] opened 2020-10-06 15:07 UTC
Reference: https://github.com/rusqlite/rusqlite/pull/812.

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1826)
┆Sprint: Backlog

**Comment by mhammond** [comment] 2020-10-08 01:46
Dupe of #3632

**Closed by mhammond** 2020-10-08 01:46 UTC
