### ISSUE TITLE
Fix a-s failing on Xcode 13 upgrade

### ISSUE THREAD

**Issue by data-sync-user** [mozilla/application-services#4494] opened 2021-09-22 03:30 UTC
```
error: Build input file cannot be found: '/Users/distiller/project/megazords/ios/MozillaAppServices/Generated/Metrics.swift' (in target 'MozillaAppServices' from project 'MozillaAppServices')

Testing failed:
	Build input file cannot be found: '/Users/distiller/project/megazords/ios/MozillaAppServices/Generated/Metrics.swift'
	Testing cancelled because the build failed.

  * TEST FAILED **

The following build commands failed:
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler (in target 'MozillaAppServices' from project 'MozillaAppServices')
(1 failure)
```

This is likely due to Xcode 13 not allowing legacy build systems to be used anymore which means we'll need to deal with anything that the new system doesn't like (which is a lot, namely putting building ios sim and ios in the same file).

Right now https://github.com/mozilla/application-services/pull/4492 seems to have gotten most but it's still failing to find Metrics.swift

┆Issue is synchronized with this [Jira Task](https://mozilla-hub.atlassian.net/browse/SYNC-2796)
┆Sprint End Date: 2021-09-30

**Comment by skhamis** [comment] 2021-09-22 04:22
Seems like the issue is that our Build phase `Generate Glean metrics` might not work with the "new build system" that is now required in XCode 13 (option been around since xcode 11 I think). So the CI cannot find the Metrics.swift anymore. Other people having this issue that I saw:

Looks like the issue is because Metrics.swift is compiled and not checked in and the CI can’t find it from my initial research:

1.) https://github.com/apollographql/apollo-ios/issues/369
2.) Xcode 12 "Build input file cannot be found" $DERIVED_FILES_DIR - https://developer.apple.com/forums/thread/661185?answerId=658857022#658857022
3.) https://developer.apple.com/forums/thread/123492

We might need to ping the glean team here to see if they ran into this issue trying to upgrade to XCode 13. 

@badboy, would you potentially be the right person to ask about this?

**Comment by badboy** [comment] 2021-09-22 08:24
Yup.
We have not yet upgraded to Xcode 13 on CI but I did install the Xcode update locally, so ... uhm ... I guess I will find out next.

I'll open a bug for it to track it and report back here.

**Comment by badboy** [comment] 2021-09-22 08:25
https://bugzilla.mozilla.org/show_bug.cgi?id=1731979

**Comment by badboy** [comment] 2021-09-22 10:34
[Glean itself works fine on Xcode 13](https://github.com/mozilla/glean/pull/1802).
It's already using the new build system in both the SDK and the sample application.
I can't get a-s to build on my M1 due to varying errors, so I can't really help at the moment.

**Closed** 2021-09-28 21:40 UTC
