### ISSUE TITLE
Add delivery manager for WebPush

### ISSUE THREAD

**Issue by jrconlin** [mozilla/application-services#1231] opened 2019-06-03 22:08 UTC
After talking to @jonalmeida, we've agreed that it would be handy for him to have the Delivery Manager component fully fleshed out Push. 

We (Jonathan, myself) need to talk about what data would be best to store and retrieve in Delivery Manager to make Jonathan's life easier.  This would be for client only.

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-93)

**Comment by jonalmeida** [comment] 2019-06-04 03:00
Is https://github.com/mozilla/application-services/issues/545 a dupe of this then?

For reference: The a-c "delivery manager" does a pretty simple check `serviceForChannelId` with the current support for just Services and WebPush as a single subscription type. 

See: https://github.com/mozilla-mobile/android-components/blob/master/components/feature/push/src/main/java/mozilla/components/feature/push/AutoPushFeature.kt#L271-L273

**Comment by vladikoff** [comment] 2019-12-13 19:20
reopen if we still need to keep an eye on this

**Closed by vladikoff** 2019-12-13 19:20 UTC
Labels: backlog, 📣 Push
