### ISSUE TITLE
A/B Testing of about:welcome sign in flow?

### ISSUE THREAD

**Issue by cse-test-sync** [mozilla/application-services#1855] opened 2019-09-23 22:53 UTC
This is a spinoff from Bug 1577690, which is about landing changes to the Firefox sign-in flow that allow users to opt-out of syncing their data.

This new bug here, is specifically about changing about:welcome to use that new technology, so that users who sign in through our generic "join firefox" messaging have the option to do so without having to upload their (encrypted) browser data to our servers. 

We infer that users will find value in this option, because we currently observe a significant number of users who disable all sync engines when signing in to Firefox, which we take a a signal that they wanted to account but not the syncing.

The required change is pretty small from a code perspective, basically removing `service=sync` from the signin URL that is opened by about:welcome when we ask the user to sign in.  There's a WIP PR for it already here:

https://github.com/mozilla/activity-stream/pull/5314/

But we should discuss the most appropriate way to roll this out.  :rfeeley suggested the possibility of an A/B test to confirm whether this changes user behavior during the onboarding flow, e.g. if we observe users opting out of sync instead of manually disabling all sync engines.

- - -
🐞 Issue is synchronized with Bugzilla [Bug 1582002](https://bugzilla.mozilla.org/show_bug.cgi?id=1582002)

┆Issue is synchronized with this [Jira Story](https://jira.mozilla.com/browse/SYNC-219)
┆Epic: Sign in to Firefox (decouple follow-up)

**Comment by data-sync-user** [comment] 2019-11-05 19:42
➤ Vladislav Filippov commented:

[~amedinac@mozilla.com] do we still want to do this or close it?

**Comment by AnaMedinac** [comment] 2019-11-12 19:53
For now the User Journey team will be testing out the UX and value proposition of the different about:welcome pages, so we should keep the downstream variables the same. We can either close the bug and revisit it later, or put it in backlog as part of phase 2 of decouple.

**Comment by rfk** [comment] 2019-12-06 06:55
The bug mirror somehow made a dupe of this, closing.

**Closed by rfk** 2019-12-06 06:55 UTC
Labels: bugzilla
