### ISSUE TITLE
FxA sign in state is unexpectedly shared between private browsing and normal browsing

### ISSUE THREAD

**Issue by mcomella** [mozilla/application-services#3828] opened 2021-01-21 19:50 UTC
### STR
- In private browsing, open https://www.mozilla.org/en-US/firefox/accounts/
- Sign in to FxA
- Switch to normal browsing tab

### Expected results
Not signed in to FxA in normal browsing

### Actual results
Signed in to FxA in normal browsing (I can see via the toolbar FxA sign in state)

Similarly, if you sign in to normal browsing, enter private browsing, and visit that page, it'll re-use your sign in state from the browser. As I was not expecting private browsing to know anything about normal browsing, this was a pretty jarring user experience.

OS: macOS
Firefox: repros in 84.0.2 & 86.0a1 (2021-01-19)

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-2016)
┆Sprint: Backlog

**Comment by mhammond** [comment] 2021-01-21 22:02
I think this should be in the Firefox for iOS repo - it's responsible for persisting the fxa state etc, and app-services knows nothing about private browsing. Sadly I can't transfer this issue (I guess because it's in a different org?)

FWIW though, it's worth noting that desktop Firefox is similar - you sign in to your account in non-private mode, but then private browsing knows you are signed in. You can even create bookmarks in private browsing mode and they sync. IIRC, desktop doesn't let you sign in to FxA in private mode, which is an explicit check made in the webchannel code - maybe that's just that Firefox for iOS should do?

**Comment by mcomella** [comment] 2021-01-23 02:19
> FWIW though, it's worth noting that desktop Firefox is similar - you sign in to your account in non-private mode, but then private browsing knows you are signed in. You can even create bookmarks in private browsing mode and they sync. IIRC, desktop doesn't let you sign in to FxA in private mode, which is an explicit check made in the webchannel code - maybe that's just what Firefox for iOS should do?

@mhammond I had actually filed this issue for desktop, not for iOS – it sounds like this is expected behavior then? In that case, I guess we can close it as WORKSFORME.

To be explicit, it doesn't match my expectations for how this should work – it feels weird that web content knows about my browser state. The bookmarks example is slightly different – it's a chrome feature that does not interact directly with web content so it feels okay that you can create bookmarks from private browsing that persist in the normal browsing state.

**Comment by rfk** [comment] 2021-01-25 04:16
Thanks for the report! I agree this is weird, but AFAICT it is indeed working as intended.

>  it feels weird that web content knows about my browser state.

In the STR when you say "Sign in to FxA", it's *signing you in to the browser* rather than (or more accurately, in addition to) signing you in to web content.

The weirdness comes from the way that we have a small number of privileged web properties that are able to query the signed-in state of the browser, in order to provide a kind of hybrid browser-state-management experience. In particular:

> if you sign in to normal browsing, enter private browsing, and visit that page, it'll re-use your sign in state from the browser.

The whole point of the `/firefox/accounts` page is to report on the signed-in state of the browser (and if you're not signed in, to guide you to do so). It's a bit weird, but IMHO it would be ever more weird for that page to say "You're not signed in, click here to sign in to Firefox and start syncing your data" when you are, in fact, already signed in and syncing your data.

I'm going to close this as `WORKSFORME`

**Closed by rfk** 2021-01-25 04:16 UTC
