### ISSUE TITLE
Bookmarks in Firefox iOS not showing up after upgrading from v63 to v65 of AppServices

### ISSUE THREAD

**Issue by nbhasin2** [mozilla/application-services#3670] opened 2020-10-28 16:50 UTC
**v63 - I am able to see all bookmarks** 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/8919439/97468227-6be65280-191b-11eb-8f92-3c5c8a525c1a.png">

**v65 - Nothing gets shown in bookmarks tab** 

<img width="584" alt="image" src="https://user-images.githubusercontent.com/8919439/97468764-05156900-191c-11eb-8c8b-b05cdedd685e.png">

┆Issue is synchronized with this [Jira Task](https://jira.mozilla.com/browse/SYNC-1861)
┆Epic: a-s consumer issues
┆Sprint: Backlog

**Comment by nbhasin2** [comment] 2020-10-28 17:00
Attaching logs

[v63_log.txt](https://github.com/mozilla/application-services/files/5453608/v63_log.txt)
[v65_log.txt](https://github.com/mozilla/application-services/files/5453609/v65_log.txt)

**Comment by eoger** [comment] 2020-10-28 18:36
Is this a release blocker? Are you set up to bisect the commits between v63 and v65?

**Comment by nbhasin2** [comment] 2020-10-28 18:46
> Is this a release blocker? 

I have pushed temporary framework so to my fork that we are not blocked on our point release v29.1
But for v30 or any other future release I'd suggest we try to fix the issue with a-s.

> Are you set up to bisect a-s between the v63 and v65 commits?

I am not currently setup to bisect a-s between the v63 and v65 commits. Will have to setup my env to do this. On top of your head do you know what might have changed? 

Working commit: cb2ce39

**Comment by mhammond** [comment] 2020-10-28 22:43
v65 has many messages like:

> objc[91846]: Class _TtC18MozillaAppServices20PlacesReadConnection is implemented in both /Users/nbhasin/Library/Developer/Xcode/DerivedData/Client-fyrtgkuylurjahempceulgjrlawt/Build/Products/Fennec-iphonesimulator/Sync.framework/Sync (0x105ecc450) and /Users/nbhasin/Library/Developer/CoreSimulator/Devices/2E739DE1-AC3A-4C7A-8323-E5DE1C968B0C/data/Containers/Bundle/Application/954A01B4-C326-40DD-9DB9-9CEED6037559/Client.app/Client (0x1044541f0). One of the two will be used. Which one is undefined.

I can see how that could cause many obscure problems and even crashes.

**Comment by data-sync-user** [comment] 2020-12-17 22:47
➤ Ryan Kelly commented:

Bumping this up into a spring since it's a blocker for basically anything we want to do on iOS.

**Comment by data-sync-user** [comment] 2020-12-18 20:08
➤ Janet Dragojevic commented:

[~jeevans@mozilla.com] [~nbhasin@mozilla.com] - if you have any updates on this, it would be great if we can revisit early in the new year.  It's related to https://github.com/mozilla/application-services/issues/3777 which is something we should prioritize resolving.

**Comment by data-sync-user** [comment] 2020-12-21 19:47
➤ Nishant Bhasin commented:

Quick update: I tested v68.1.0 last week and that build has same issue where bookmarks don't show up. After testing that I informed Ryan Kelly about this and mentioned in the channel too.

**Comment by rfk** [comment] 2020-12-22 06:41
Confirmed that this reproduces in a local build against latest `main` using [these instructions](https://github.com/mozilla/application-services/blob/main/docs/howtos/locally-published-components-in-ios.md).

I added a bit of light diagnostic logging and it looks like `getBookmarksTree` is returning an error, which is being silently ignored by firefox-ios [here](https://github.com/mozilla-mobile/firefox-ios/blob/ca2f5c98dd25b8f3026b2bd976450edff1853172/Client/Frontend/Library/BookmarksPanel.swift#L171). I'll keep digging.

**Comment by rfk** [comment] 2020-12-22 06:45
If I turn [`guard let folder = result.successValue as? BookmarkFolder`](https://github.com/mozilla-mobile/firefox-ios/blob/ca2f5c98dd25b8f3026b2bd976450edff1853172/Client/Frontend/Library/BookmarksPanel.swift#L170) into `let folder = result.successValue as! BookmarkFolder` then it throws this delightful error:

```
Could not cast value of type 'MozillaAppServices.BookmarkFolder' (0x1121fec10) to 'MozillaAppServices.BookmarkFolder' (0x11075c310).
```

So yeah, I think the the log lines that @mhammond noted above are key here, especially where it says:

```
Class _TtC18MozillaAppServices14BookmarkFolder is implemented in both /Users/rfk/Library/Developer/Xcode/DerivedData/Client-csrpomxftoicgfbdjzdhxtbsadey/Build/Products/Fennec-iphonesimulator/Sync.framework/Sync (0x1121fec10) and /Users/rfk/Library/Developer/CoreSimulator/Devices/76E6DA8A-9C0B-43EA-9B52-E2E208377B19/data/Containers/Bundle/Application/83B0DDF0-AEC7-4747-B417-2A17187CCB94/Client.app/Client (0x11075c310). One of the two will be used. Which one is undefined.
```

I think we're receiving a `BookmarkFolder` object defined in one place and then trying to cast it to the `BookmarkFolder` defined in the other place.

I really don't know enough about Swift and Carthage and XCode to know what to look at next here :-/

**Comment by rfk** [comment] 2020-12-22 09:09
I tried making a local build of the `v63.0.0` tag of application services, although I had to apply some [local fixes](https://github.com/mozilla/application-services/pull/3789/) to get it working. Using that local build in firefox-ios appears to show the same error with duplicate type definitions for `MozillaAppServices.BookmarkFolder`.

So, I feel like this must be something that's changed in the build setup rather than in the appservices code itself.

Next I'm going to try using [the same commit](https://github.com/nbhasin2/application-services/commit/cb2ce39c76c26302f8ea97339c6846c2959cd921) as @nbhasin2 used for the custom [`v63.0b` tag](https://github.com/nbhasin2/application-services/releases/tag/63.0b) that is currently used by firefox-ios and which doesn't seem to exhibit this issue. Unfortunately I don't think I can test with that release directly because I'm on a new XCode and hitting [this issue](https://github.com/mozilla/application-services/issues/3769).

**Comment by rfk** [comment] 2020-12-22 10:04
>  Next I'm going to try using the same commit as @nbhasin2 used for the custom v63.0b tag

Building from this tag also exhibits the "blank bookmarks screen" behaviour. In other words, I'm totally unable to produce a build of firefox-ios in which bookmarks are working. I may need to try downgrading xcode so that I can build with the published binary artifacts, but I'm out of time for today.

**Comment by rfk** [comment] 2020-12-23 04:50
Another observation: I futzed around with the latest `main` of appservices and configured it to build as a *dynamically-linked* framework rather than as a statically-linked one. Building firefox-ios against this shows bookmarks working as expected!

I recall us having good reasons to prefer static linking over dynamic (faster app startup, maybe smaller app size?) but perhaps switching to dynamic linking could be a good fallback option if we can't figure out what's going wrong with the statically-linked case here.

**Comment by rfk** [comment] 2020-12-24 00:31
I installed XCode 12.0.0 so I could try using the last-known-working prebuilt release of appservices.

Building firefox-ios locally with the prebuilt [appservices v63.0b](https://github.com/nbhasin2/application-services/releases/tag/63.0b), bookmarks work correctly and I do not see the warnings about duplicate symbols. So at least I can produce a working build!

If I build appservices locally using the [exact same commit](https://github.com/nbhasin2/application-services/commit/cb2ce39c76c26302f8ea97339c6846c2959cd921) and XCode 12.0.0, and then build firefox-ios against the resulting framework, I once again see the blank bookmarks screen and the duplicate symbols warnings.

@nbhasin2 that pre-built `v63.0b` release, was that something built for CircleCI or did you need to build it locally and upload the release artifacts? Was there anything unusual about the way it was built?

**Comment by rfk** [comment] 2020-12-24 01:52
I'm going to have to put this down for the holiday break, but I wanted to leave a bit of braindump after my deep dive.

First, a caveat: I am by no means an expert on iOS or XCode build stuff, I've just been muddling my way through things here and doing a lot of googling. If I say something below that doesn't sound right, please point it out to me, my mental model is very likely to contain inaccuracies!

---

Background: appservices

For each appservices release, we publish a pre-built `MozillaAppservices.framework` artifact. I believe the intention behind publishing a pre-built artifact is to avoid requiring iOS devs to have the rust toolchain installed and up-to-date. This build is driven by Carthage and the XCode project config in `./megazords/ios/MozillaAppServices.xcodeproj`.

This is configured to build as a *static framework* (via `MACH_O_TYPE = staticlib` in XCode) meaning consumers will directly incorporate the code into their build artifacts, rather than bundling it as a dylib.

For swift-compilation-toolchain-reasons, firefox-ios can only use this pre-built framework if it is compiled with the exact same version of swift as the one being used to compile firefox-ios (ref https://github.com/mozilla/application-services/issues/3769 for details). Thus, we periodically need to bump the version of XCode used to build our releases in order to track what's being used in firefox-ios.

Currently firefox-ios is using XCode 12 (I think 12.0?), and we updated our release pipeline to use XCode 12 as of appservices `v64.0.0`. This included a little bit of hackery get Carthage and XCode 12 working nicely together, which I don't really understand but apparently has something to do with disabling new build targets for Apple silicon..? Anyway, releases from v64 are built using XCode 12.0.0.

Unfortunately, firefox-ios has never been able to successfully incorporate one of these releases into their build. Whenever they try to update past appservices `v63`, bookmarks stop working as described in this issue.

To make new releases built using XCode 12, firefox-ios currently depends on a [custom release v63.0b](https://github.com/nbhasin2/application-services/releases/tag/63.0b) of appservices which was built by @nbhasin2. I don't know the particulars of how this was built, only that it does not exhibit the bug under investigation here.

---

Background: firefox-ios

The XCode project config for firefox-ios has a couple of different build targets of interest.  The main application is an executable target named `Client`. This depends on a dynamically-linked framework named `Sync.framework` that includes much of the sync-and-storage-related code. This in turn depends on a static library target named `Storage` which is configured to link against `MozillaAppServices.framework`.

I won't pretend to have any insight into why the artifacts are arranged in this way.

As far as I can tell, the main `Client` target is not configured to link against `MozillaApplicationServices.framework`, but it *does* include several files that `import MozillaAppServices`. I think the expectation is that it will resolve those imports against `Sync.framework`, but I don't know enough about XCode to know whether or where that expectation is captured explicitly.

Without understanding the details, I find something about this setup a bit suspicious. Both the `Client` target and the `Sync.framework` target contain code that does `import MozillaAppServices`. This means we have two separate compilation artifacts that are importing from a static library, so I'm not terribly surprised to find us encountering errors relates to duplicate symbols from that library. Naively, I'm more surprised that it ever worked than I am that it has stopped working! But that impression is likely due to my own ignorance about the details here.

---

So, what's changed?

I don't know, but something sure has. @nbhasin2 shared with me the compiled artifacts from the latest release of firefox-ios, which includes the custom appservices `v63.0b`. I unpacked it and poked around at the relationship between the main `Client` executable and the `Sync` dynamic library.

(All of this is based on my own limited understanding of symbols etc in these libraries).

We can see that the main `Client` executable doesn't contain any references to the `bookmarks_get_tree` function, and it knows that if it wants to use the `BookmarkFolder` type then it should look on the `Sync` dylib:

```
[rfk] IPA/Payload/Client.app % file Client 
Client: Mach-O 64-bit executable arm64
[rfk] IPA/Payload/Client.app % nm -mg Client | grep -i "bookmark.*tree"  
[rfk] IPA/Payload/Client.app % nm -mg Client | grep -i "14bookmarkfolder"
                 (undefined) external _$s18MozillaAppServices14BookmarkFolderCMa (from Sync)
                 (undefined) external _$s18MozillaAppServices14BookmarkFolderCMn (from Sync)
[rfk] IPA/Payload/Client.app % 
```

We also see that the `Sync` framework dylib contains definitions for these functions and symbols, as expected:

```
[rfk] IPA/Payload/Client.app % file ./Frameworks/Sync.framework/Sync
./Frameworks/Sync.framework/Sync: Mach-O 64-bit dynamically linked shared library arm64
[rfk] IPA/Payload/Client.app % nm -mg ./Frameworks/Sync.framework/Sync | grep -i "bookmark.*tree"
000000000020ed94 (__TEXT,__text) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKF
00000000016382e4 (__TEXT,__const) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKFTq
[...snip...]
00000000009e27b8 (__TEXT,__text) external __ZN89_$LT$places..storage..bookmarks..UpdateTreeLocation$u20$as$u20$core..default..Default$GT$7default17ha2e0fc6651e09084E
0000000000887704 (__TEXT,__text) external _bookmarks_get_tree
[rfk] IPA/Payload/Client.app % 
[rfk] IPA/Payload/Client.app % nm -mg ./Frameworks/Sync.framework/Sync | grep -i "14bookmarkfolder"
000000000024ea7c (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvg
0000000001639360 (__TEXT,__const) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvpMV
[...snip...]
000000000024ee20 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCfD
000000000024edc0 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCfd
```

If I make a local build using the pre-built `63.0b` artifact, I see similar results (except that they're x86_64 binaries, because they're compiled for the simulator.

Now, compare that to the artifacts produced using a local build of the `63.0b` tag, which exhibits this empty-bookmarks-page problem. The main `Client` executable suddenly wants to link in the `bookmarks_get_tree` function from the `Sync` framework, and it contains its own definitions of  the `BookmarkFolder` type symbols:

```
[rfk] Products/Fennec-iphonesimulator/Client.app % file Client                                                       
Client: Mach-O 64-bit executable x86_64
[rfk] Products/Fennec-iphonesimulator/Client.app % nm -mg Client | grep -i "bookmark.*tree"                          
00000001006d8e20 (__TEXT,__text) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKF
000000010074c0c4 (__TEXT,__const) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKFTq
                 (undefined) external _bookmarks_get_tree (from Sync)
[rfk] Products/Fennec-iphonesimulator/Client.app % 
[rfk] Products/Fennec-iphonesimulator/Client.app % nm -mg Client | grep -i "14bookmarkfolder"                        
00000001006f0980 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvg
000000010074ce40 (__TEXT,__const) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvpMV
[...snip...]
00000001006f0da0 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCMa
00000001008633a8 (__DATA,__data) external _$s18MozillaAppServices14BookmarkFolderCMm
000000010074d038 (__TEXT,__const) external _$s18MozillaAppServices14BookmarkFolderCMn
00000001008633e0 (__DATA,__data) external _$s18MozillaAppServices14BookmarkFolderCN
[...snip...]
```

While the `Sync` framework dylib has its own versions of those bookmark-folder related symbols:

```
[rfk] Products/Fennec-iphonesimulator/Client.app % file ./Frameworks/Sync.framework/Sync                             
./Frameworks/Sync.framework/Sync: Mach-O 64-bit dynamically linked shared library x86_64
[rfk] Products/Fennec-iphonesimulator/Client.app % nm -mg ./Frameworks/Sync.framework/Sync | grep -i "bookmark.*tree"  
0000000000345c20 (__TEXT,__text) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKF
0000000000aee3e4 (__TEXT,__const) external _$s18MozillaAppServices20PlacesReadConnectionC16getBookmarksTree8rootGUID9recursiveAA12BookmarkNodeCSgSS_SbtKFTq
[...snip...]
000000000063feb8 (__TEXT,__text) external __ZN77_$LT$places..bookmark_sync..store..Merger$u20$as$u20$dogear..store..Store$GT$17fetch_remote_tree17h84cdce67e6e58b9eE
000000000067b2dc (__TEXT,__text) external _bookmarks_get_tree
[rfk] Products/Fennec-iphonesimulator/Client.app % nm -mg ./Frameworks/Sync.framework/Sync | grep -i "14bookmarkfolder"
0000000000372920 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvg
0000000000aefc60 (__TEXT,__const) external _$s18MozillaAppServices14BookmarkFolderC10childGUIDsSaySSGvpMV
[...snip...]
0000000000372d40 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCMa
0000000000d42390 (__DATA,__data) external _$s18MozillaAppServices14BookmarkFolderCMm
0000000000aefe58 (__TEXT,__const) external _$s18MozillaAppServices14BookmarkFolderCMn
0000000000d423c8 (__DATA,__data) external _$s18MozillaAppServices14BookmarkFolderCN
0000000000372a90 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCfD
0000000000372a50 (__TEXT,__text) external _$s18MozillaAppServices14BookmarkFolderCfd
```

So IIUC, the `Client` executable is going to try to call the `bookmarks_get_tree` function exported by the `Sync` framework dylib, but it’s then going to use its own copy of the `BookmarkFolder` type to try to deal with the resulting value. Which yeah, is not going to go well.

I don’t have any good ideas about what might be triggering this different in behaviour, but it seems clear this is some sort of build/link issue.

**Comment by rfk** [comment] 2020-12-24 01:59
Here's possibly an even simpler demonstration of the problem. Current release:

```
[rfk] IPA/Payload/Client.app % grep -r getBookmarksTree *
Binary file Frameworks/Sync.framework/Sync matches
```

Broken local build:

```
[rfk] Products/Fennec-iphonesimulator/Client.app % grep -r getBookmarksTree *
Binary file Client matches
Binary file Frameworks/Sync.framework/Sync matches
```

In the broken build, the main `Client` executable seems to have its own duplicate copy of the `MozillaAppServices.PlacesReadConnection.getBookmarksTree` method.

**Comment by rfk** [comment] 2020-12-24 02:03
@nbhasin2 I'd also be curious your thoughts on moving to a dynamiclly-linked `MozillaAppServices.framework` since that does seem to resolve the issue here. I don't have good visibility into what impact that might have on the firefox-ios application.

**Comment by nbhasin2** [comment] 2020-12-24 16:47
@rfk The duplication is a big concern for statically linked binary. I am going to start investigating the impact of dynamically linked binary but from what I recall it was bloating our app (> 100MB) and thus we decided to link it statically.

**Comment by data-sync-user** [comment] 2021-01-13 18:51
➤ Janet Dragojevic commented:

Nish is currently working on this in the current iOS sprint.

**Comment by rfk** [comment] 2021-01-14 01:42
> The duplication is a big concern for statically linked binary. I am going to start investigating the impact of dynamically
> linked binary but from what I recall it was bloating our app (> 100MB) and thus we decided to link it statically.

One quick note here - if dynamic linking turns out to make the build more robust but the file size is an issue, we could look at making a "custom megazord" build for firefox-ios that only contains the components that you actually use.

**Comment by nbhasin2** [comment] 2021-01-14 01:50
@rfk I spent more time and basically made everything dynamically linked and still saw an issue where the casting of bookmarks wasn't working. Basically the successvalue is never of type BookmarkFolder and is always of type BookmarkNode and casting doesn't work. 

I am trying something on Firefox iOS side to make a wrapper for bookmarks and look more into why when we link Mozilla AppServices with iOS it doesn't respect casting from BookmarkNode to BookmakrFolder. 

Let me sync up with you tomorrow if you have time and I can give you more details. Maybe we can find a common ground and tackle this together. 

```
        profile.places.getBookmarksTree(rootGUID: bookmarkFolderGUID, recursive: false).uponQueue(.main) { result in
             //Issue: The success value is never of type BookmarkFolder
            guard let folder = result.successValue as? BookmarkFolder else {
                // TODO: Handle error case?
                self.bookmarkFolder = nil
                self.bookmarkNodes = []
                self.recentBookmarks = []
                return
            }
```

**lines:**
https://github.com/mozilla-mobile/firefox-ios/blob/main/Client/Frontend/Library/BookmarksPanel.swift#L168-L176

**Comment by nbhasin2** [comment] 2021-01-14 01:51
All this testing is happening with latest XCode12.3 and I am running a compiled version of A~S from main branch.

**Comment by rfk** [comment] 2021-01-28 22:52
> I spent more time and basically made everything dynamically linked and still saw an issue where the casting of
> bookmarks wasn't working

Just surfacing some context from a zoom meeting between @nbhasin2 and I: when he observe the issue described above, he had changed all the iOS build steps to link dynamically, but the appservices framework was still being built as a static lib. (@nbhasin2 please correct me if I've misremembered or misunderstood here).

The [v69.0.0 release](https://github.com/mozilla/application-services/releases/tag/v69.0.0) of appservices builds as a dylib rather than a static lib, so IIUC we should be in a good position to try again on updating the versions here.

**Comment by nbhasin2** [comment] 2021-01-28 22:56
@rfk I have been posting my updates in a FxiOS ticket, Going to try out new build and see if all works 
I was able to make everything work locally when you were away so I believe this v69.0.0 will also work 🤞🏼 

https://github.com/mozilla-mobile/firefox-ios/issues/7851

**Closed** 2021-02-01 20:33 UTC
